
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  2 2026 11:24:45 +06 (May  2 2026 05:24:45 UTC)

// Verification Directory fv/top 

module top(SYS_CLOCK, SRST, X0, X1, X2, X3, C0, C1, C2, C3, Y);
  input SYS_CLOCK, SRST;
  input [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  output [9:0] Y;
  wire SYS_CLOCK, SRST;
  wire [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  wire [9:0] Y;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6, WALLACE_CSA_DUMMY_OP_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_8,
       WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_24,
       WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_32,
       WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_48,
       WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_57,
       WALLACE_CSA_DUMMY_OP_groupi_n_58,
       WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66,
       WALLACE_CSA_DUMMY_OP_groupi_n_67,
       WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_72,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74,
       WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_76,
       WALLACE_CSA_DUMMY_OP_groupi_n_77,
       WALLACE_CSA_DUMMY_OP_groupi_n_78,
       WALLACE_CSA_DUMMY_OP_groupi_n_79;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_80,
       WALLACE_CSA_DUMMY_OP_groupi_n_81,
       WALLACE_CSA_DUMMY_OP_groupi_n_82,
       WALLACE_CSA_DUMMY_OP_groupi_n_83,
       WALLACE_CSA_DUMMY_OP_groupi_n_84,
       WALLACE_CSA_DUMMY_OP_groupi_n_85,
       WALLACE_CSA_DUMMY_OP_groupi_n_86,
       WALLACE_CSA_DUMMY_OP_groupi_n_87;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_88,
       WALLACE_CSA_DUMMY_OP_groupi_n_89,
       WALLACE_CSA_DUMMY_OP_groupi_n_90,
       WALLACE_CSA_DUMMY_OP_groupi_n_91,
       WALLACE_CSA_DUMMY_OP_groupi_n_92,
       WALLACE_CSA_DUMMY_OP_groupi_n_93,
       WALLACE_CSA_DUMMY_OP_groupi_n_94,
       WALLACE_CSA_DUMMY_OP_groupi_n_95;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_96,
       WALLACE_CSA_DUMMY_OP_groupi_n_97,
       WALLACE_CSA_DUMMY_OP_groupi_n_98,
       WALLACE_CSA_DUMMY_OP_groupi_n_99,
       WALLACE_CSA_DUMMY_OP_groupi_n_100,
       WALLACE_CSA_DUMMY_OP_groupi_n_101,
       WALLACE_CSA_DUMMY_OP_groupi_n_102,
       WALLACE_CSA_DUMMY_OP_groupi_n_103;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_104,
       WALLACE_CSA_DUMMY_OP_groupi_n_105,
       WALLACE_CSA_DUMMY_OP_groupi_n_106,
       WALLACE_CSA_DUMMY_OP_groupi_n_107,
       WALLACE_CSA_DUMMY_OP_groupi_n_108,
       WALLACE_CSA_DUMMY_OP_groupi_n_109,
       WALLACE_CSA_DUMMY_OP_groupi_n_110,
       WALLACE_CSA_DUMMY_OP_groupi_n_111;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_112,
       WALLACE_CSA_DUMMY_OP_groupi_n_113,
       WALLACE_CSA_DUMMY_OP_groupi_n_114,
       WALLACE_CSA_DUMMY_OP_groupi_n_116,
       WALLACE_CSA_DUMMY_OP_groupi_n_117,
       WALLACE_CSA_DUMMY_OP_groupi_n_118,
       WALLACE_CSA_DUMMY_OP_groupi_n_119,
       WALLACE_CSA_DUMMY_OP_groupi_n_120;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_121,
       WALLACE_CSA_DUMMY_OP_groupi_n_122,
       WALLACE_CSA_DUMMY_OP_groupi_n_123,
       WALLACE_CSA_DUMMY_OP_groupi_n_124,
       WALLACE_CSA_DUMMY_OP_groupi_n_125,
       WALLACE_CSA_DUMMY_OP_groupi_n_126,
       WALLACE_CSA_DUMMY_OP_groupi_n_127,
       WALLACE_CSA_DUMMY_OP_groupi_n_128;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_129,
       WALLACE_CSA_DUMMY_OP_groupi_n_130,
       WALLACE_CSA_DUMMY_OP_groupi_n_131,
       WALLACE_CSA_DUMMY_OP_groupi_n_132,
       WALLACE_CSA_DUMMY_OP_groupi_n_133,
       WALLACE_CSA_DUMMY_OP_groupi_n_134,
       WALLACE_CSA_DUMMY_OP_groupi_n_135,
       WALLACE_CSA_DUMMY_OP_groupi_n_136;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_137,
       WALLACE_CSA_DUMMY_OP_groupi_n_138,
       WALLACE_CSA_DUMMY_OP_groupi_n_139,
       WALLACE_CSA_DUMMY_OP_groupi_n_140,
       WALLACE_CSA_DUMMY_OP_groupi_n_141,
       WALLACE_CSA_DUMMY_OP_groupi_n_142,
       WALLACE_CSA_DUMMY_OP_groupi_n_143,
       WALLACE_CSA_DUMMY_OP_groupi_n_144;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_145,
       WALLACE_CSA_DUMMY_OP_groupi_n_146,
       WALLACE_CSA_DUMMY_OP_groupi_n_147,
       WALLACE_CSA_DUMMY_OP_groupi_n_148,
       WALLACE_CSA_DUMMY_OP_groupi_n_150,
       WALLACE_CSA_DUMMY_OP_groupi_n_151,
       WALLACE_CSA_DUMMY_OP_groupi_n_152,
       WALLACE_CSA_DUMMY_OP_groupi_n_153;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_154,
       WALLACE_CSA_DUMMY_OP_groupi_n_155,
       WALLACE_CSA_DUMMY_OP_groupi_n_156,
       WALLACE_CSA_DUMMY_OP_groupi_n_157,
       WALLACE_CSA_DUMMY_OP_groupi_n_158,
       WALLACE_CSA_DUMMY_OP_groupi_n_159,
       WALLACE_CSA_DUMMY_OP_groupi_n_160,
       WALLACE_CSA_DUMMY_OP_groupi_n_161;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_162,
       WALLACE_CSA_DUMMY_OP_groupi_n_163,
       WALLACE_CSA_DUMMY_OP_groupi_n_164,
       WALLACE_CSA_DUMMY_OP_groupi_n_166,
       WALLACE_CSA_DUMMY_OP_groupi_n_167,
       WALLACE_CSA_DUMMY_OP_groupi_n_168,
       WALLACE_CSA_DUMMY_OP_groupi_n_169,
       WALLACE_CSA_DUMMY_OP_groupi_n_170;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_171,
       WALLACE_CSA_DUMMY_OP_groupi_n_172,
       WALLACE_CSA_DUMMY_OP_groupi_n_174,
       WALLACE_CSA_DUMMY_OP_groupi_n_176,
       WALLACE_CSA_DUMMY_OP_groupi_n_178,
       WALLACE_CSA_DUMMY_OP_groupi_n_180, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52;
  DFFQX1HVT \Y_reg[9] (.CK (SYS_CLOCK), .D (n_8), .Q (Y[9]));
  DFFQX1HVT \Y_reg[8] (.CK (SYS_CLOCK), .D (n_7), .Q (Y[8]));
  DFFQX1HVT \Y_reg[6] (.CK (SYS_CLOCK), .D (n_6), .Q (Y[6]));
  DFFQX1HVT \Y_reg[2] (.CK (SYS_CLOCK), .D (n_4), .Q (Y[2]));
  DFFQX1HVT \Y_reg[1] (.CK (SYS_CLOCK), .D (n_1), .Q (Y[1]));
  DFFQX1HVT \Y_reg[5] (.CK (SYS_CLOCK), .D (n_5), .Q (Y[5]));
  DFFQX1HVT \Y_reg[0] (.CK (SYS_CLOCK), .D (n_0), .Q (Y[0]));
  DFFQX1HVT \Y_reg[7] (.CK (SYS_CLOCK), .D (n_9), .Q (Y[7]));
  DFFQX1HVT \Y_reg[4] (.CK (SYS_CLOCK), .D (n_2), .Q (Y[4]));
  DFFQX1HVT \Y_reg[3] (.CK (SYS_CLOCK), .D (n_3), .Q (Y[3]));
  NOR2BX1HVT g37__2398(.AN (n_45), .B (SRST), .Y (n_9));
  NOR2BX1HVT g38__5107(.AN (n_43), .B (SRST), .Y (n_8));
  NOR2BX1HVT g39__6260(.AN (n_44), .B (SRST), .Y (n_7));
  NOR2BX1HVT g40__4319(.AN (n_46), .B (SRST), .Y (n_6));
  NOR2BX1HVT g41__8428(.AN (n_47), .B (SRST), .Y (n_5));
  NOR2BX1HVT g42__5526(.AN (n_50), .B (SRST), .Y (n_4));
  NOR2BX1HVT g43__6783(.AN (n_49), .B (SRST), .Y (n_3));
  NOR2BX1HVT g44__3680(.AN (n_48), .B (SRST), .Y (n_2));
  NOR2BX1HVT g45__1617(.AN (n_51), .B (SRST), .Y (n_1));
  NOR2BX1HVT g46__2802(.AN (n_52), .B (SRST), .Y (n_0));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g3118__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .CO (n_43), .S (n_44));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3119__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_167), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .S (n_45));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3120__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_171), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .S (n_46));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3121__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_169), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .S (n_47));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_g3122__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_163), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .S (n_48));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3123__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_153), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_157), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .S (n_49));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3124__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_145), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_159), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_171));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3125__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_141), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_161), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_169));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3126__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_139), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_167));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3127__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_135), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_151), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .S (n_50));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3128__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_152), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_147), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_155), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_163));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3129__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_143), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_161));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3130__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_118), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_159));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3131__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_125), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_131), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_157));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3132__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_117), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_137), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_155));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3133__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_121), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_152), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_153));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3134__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_123), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_151));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3135__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_114), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_127), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .S (n_51));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3136__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_111), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_129), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_147));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3137__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_99), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_112), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_133), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_145));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3138__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_110), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_143));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3139__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_113), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_119), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_116), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_141));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3140__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_98), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_139));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3141__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_137));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3142__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_109), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_89), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_103), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_135));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3143__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_133));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3144__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_91), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_95), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_105), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_131));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3145__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_129));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3146__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_101), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_127));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3147__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_102), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_81), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_125));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3148__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_100), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_123));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3149__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_121));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3150__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_118), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_119));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3151__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_116), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_117));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3152__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_107), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_114), .S (n_52));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3153__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_112), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_113));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3154__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_110), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_111));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3155__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_109));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3156__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_107));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3157__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_105));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3158__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_102), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_103));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3159__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_100), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_101));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3160__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_98), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_99));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3161__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_97));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3162__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_95));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3163__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_93));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3164__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_91));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3165__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_89));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3166__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_87));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3167__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_85));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3168__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_83));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3169__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_81));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3170__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3171__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_77));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3172__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_75));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3173__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_73));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3174__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_71));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3175__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_69));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3176__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_67));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g3177__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_65));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3178__6131(.A (C2[2]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3179__1881(.A (C2[2]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3180__5115(.A (C3[2]), .B
       (X3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_61));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3181__7482(.A (C3[1]), .B
       (X3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3182__4733(.A (C2[3]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3183__6161(.A (C2[3]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3184__9315(.A (C3[1]), .B
       (X3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_57));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3185__9945(.A (C0[2]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3186__2883(.A (C3[1]), .B
       (X3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3187__2346(.A (C2[1]), .B
       (X2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_54));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3188__1666(.A (C0[0]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_53));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3189__7410(.A (C3[2]), .B
       (X3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3190__6417(.A (C2[3]), .B
       (X2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3191__5477(.A (C3[3]), .B
       (X3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3192__2398(.A (C3[1]), .B
       (X3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3193__5107(.A (C3[0]), .B
       (X3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_48));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3194__6260(.A (C0[2]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3195__4319(.A (C1[2]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3196__8428(.A (C0[1]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3197__5526(.A (C1[0]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3198__6783(.A (C0[1]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3199__3680(.A (C0[3]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3200__1617(.A (C1[3]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3201__2802(.A (C0[1]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3202__1705(.A (C0[1]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3203__5122(.A (C0[0]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3204__8246(.A (C1[1]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3205__7098(.A (C1[0]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3206__6131(.A (C3[0]), .B
       (X3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3207__1881(.A (C3[2]), .B
       (X3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3208__5115(.A (C0[2]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3209__7482(.A (C0[0]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3210__4733(.A (C0[0]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3211__6161(.A (C2[0]), .B
       (X2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3212__9315(.A (C2[3]), .B
       (X2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3213__9945(.A (C3[3]), .B
       (X3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3214__2883(.A (C3[3]), .B
       (X3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3215__2346(.A (C2[1]), .B
       (X2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3216__1666(.A (C3[3]), .B
       (X3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3217__7410(.A (C3[2]), .B
       (X3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3218__6417(.A (C1[2]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3219__5477(.A (C3[0]), .B
       (X3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3220__2398(.A (C2[0]), .B
       (X2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3221__5107(.A (C0[3]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3222__6260(.A (C1[3]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3223__4319(.A (C1[0]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3224__8428(.A (C1[2]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3225__5526(.A (C2[1]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3226__6783(.A (C0[3]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3227__3680(.A (C2[0]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3228__1617(.A (C0[3]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3229__2802(.A (C0[2]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3230__1705(.A (C1[1]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3231__5122(.A (C1[2]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3232__8246(.A (C1[1]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3233__7098(.A (C1[1]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3234__6131(.A (C3[0]), .B
       (X3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3235__1881(.A (C1[0]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3236__5115(.A (C2[2]), .B
       (X2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3237__7482(.A (C2[1]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3238__4733(.A (C1[3]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3239__6161(.A (C2[0]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3240__9315(.A (C2[2]), .B
       (X2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g3241__9945(.A (C1[3]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_0));
endmodule

