
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  2 2026 12:19:01 +06 (May  2 2026 06:19:01 UTC)

// Verification Directory fv/MAC_4BIT 

module MAC_4BIT(SYS_CLOCK, SRST, A, B, Y);
  input SYS_CLOCK, SRST;
  input [3:0] A, B;
  output [7:0] Y;
  wire SYS_CLOCK, SRST;
  wire [3:0] A, B;
  wire [7:0] Y;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6, WALLACE_CSA_DUMMY_OP_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_8,
       WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_24,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_32;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_48;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  DFFX1 \Y_reg[6] (.CK (SYS_CLOCK), .D (n_14), .Q (Y[6]), .QN
       (UNCONNECTED));
  DFFX1 \Y_reg[1] (.CK (SYS_CLOCK), .D (n_11), .Q (Y[1]), .QN
       (UNCONNECTED0));
  DFFX1 \Y_reg[0] (.CK (SYS_CLOCK), .D (n_8), .Q (Y[0]), .QN
       (UNCONNECTED1));
  DFFX1 \Y_reg[7] (.CK (SYS_CLOCK), .D (n_13), .Q (Y[7]), .QN
       (UNCONNECTED2));
  DFFX1 \Y_reg[4] (.CK (SYS_CLOCK), .D (n_12), .Q (Y[4]), .QN
       (UNCONNECTED3));
  DFFX1 \Y_reg[3] (.CK (SYS_CLOCK), .D (n_9), .Q (Y[3]), .QN
       (UNCONNECTED4));
  DFFX1 \Y_reg[2] (.CK (SYS_CLOCK), .D (n_10), .Q (Y[2]), .QN
       (UNCONNECTED5));
  DFFX1 \Y_reg[5] (.CK (SYS_CLOCK), .D (n_15), .Q (Y[5]), .QN
       (UNCONNECTED6));
  NOR2X1 g22__2398(.A (SRST), .B (n_6), .Y (n_15));
  NOR2X1 g23__5107(.A (SRST), .B (n_7), .Y (n_14));
  NOR2X1 g24__6260(.A (SRST), .B (n_0), .Y (n_13));
  NOR2X1 g25__4319(.A (SRST), .B (n_5), .Y (n_12));
  NOR2X1 g26__8428(.A (SRST), .B (n_2), .Y (n_11));
  NOR2X1 g27__5526(.A (SRST), .B (n_3), .Y (n_10));
  NOR2X1 g28__6783(.A (SRST), .B (n_4), .Y (n_9));
  NOR2X1 g29__3680(.A (SRST), .B (n_1), .Y (n_8));
  CLKINVX1 g30(.A (n_26), .Y (n_7));
  CLKINVX1 g31(.A (n_27), .Y (n_6));
  CLKINVX1 g32(.A (n_28), .Y (n_5));
  CLKINVX1 g33(.A (n_29), .Y (n_4));
  CLKINVX1 g34(.A (n_30), .Y (n_3));
  CLKINVX1 g35(.A (n_31), .Y (n_2));
  CLKINVX1 g36(.A (n_32), .Y (n_1));
  CLKINVX1 g37(.A (n_25), .Y (n_0));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd1__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .B (Y[1]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .S (n_31));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd2__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B (Y[2]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .S (n_30));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd3__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .B (Y[3]), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .S (n_29));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd4__5122(.A (Y[4]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .S (n_28));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd5__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .S (n_27));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd6__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .S (n_26));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd7__6131(.A (Y[7]), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .S (n_25));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_0__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_0__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_1__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_0__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_1__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_0__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_1__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CI (Y[5]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_006_0__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .CI (Y[6]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  ADDHX1 WALLACE_CSA_DUMMY_OP_groupi_g137__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .B (Y[0]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .S (n_32));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g138__1666(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g139__7410(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g140__6417(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g141__5477(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g142__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g143__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g144__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g145__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g146__8428(.A (A[2]), .B (B[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g147__5526(.A (A[2]), .B (B[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g148__6783(.A (A[1]), .B (B[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g149__3680(.A (A[3]), .B (B[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g150__1617(.A (B[2]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g151__2802(.A (B[0]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g152__1705(.A (B[0]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g153__5122(.A (B[1]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g154__8246(.A (A[2]), .B (B[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g155__7098(.A (A[3]), .B (B[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g156__6131(.A (A[1]), .B (B[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g157__1881(.A (B[1]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g158__5115(.A (A[0]), .B (B[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_0));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g159__7482(.A (B[3]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g160__4733(.A (B[0]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g161__6161(.A (B[3]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
endmodule

