######################################################################

# Created by Genus(TM) Synthesis Solution 21.18-s082_1 on Sat May 02 11:06:30 +06 2026

# This file contains the Genus script for design:top

######################################################################

set_db -quiet information_level 7
set_db -quiet init_lib_search_path {. ../LIB $TECH_DIR}
set_db -quiet design_mode_process 60.0
set_db -quiet phys_assume_met_fill 0.0
set_db -quiet map_placed_for_route_early_global false
set_db -quiet phys_use_invs_extraction true
set_db -quiet phys_route_time_out 120.0
set_db -quiet db_units 2000
set_db -quiet capacitance_per_unit_length_mmmc {}
set_db -quiet resistance_per_unit_length_mmmc {}
set_db -quiet runtime_by_stage {{PBS_Generic-Start 0 23 0.0 23.997444} {to_generic 7 30 6 30} {first_condense 2 32 2 33} {PBS_Generic_Opt-Post 9 32 8.212069999999997 32.209514} {{PBS_Generic-Postgen HBO Optimizations} 0 32 0.0 32.209514} {PBS_TechMap-Start 0 35 0.0 34.203937} {{PBS_TechMap-Premap HBO Optimizations} 0 35 0.0 34.203937} {second_condense 1 36 2 38} {reify 11 47 20 58} {global_incr_map 0 47 0 59} {{PBS_Techmap-Global Mapping} 12 47 13.169599999999996 47.373537} {{PBS_TechMap-Datapath Postmap Operations} 2 50 2.9993050000000068 50.372842000000006} {{PBS_TechMap-Postmap HBO Optimizations} 0 50 -0.002029000000007386 50.370813} {{PBS_TechMap-Postmap Clock Gating} 0 50 0.0 50.370813} {{PBS_TechMap-Postmap Cleanup} 1 51 0.9995520000000013 51.370365} {PBS_Techmap-Post_MBCI 0 51 0.0 51.370365} {incr_opt 0 53 0 64} }
set_db -quiet timing_adjust_tns_of_complex_flops false
set_db -quiet tinfo_tstamp_file .rs_B2_Robiul.tstamp
set_db -quiet metric_enable true
set_db -quiet use_area_from_lef true
set_db -quiet flow_metrics_snapshot_uuid 28dad1a7-6d91-4ac7-957b-557f523d4253
set_db -quiet phys_use_segment_parasitics true
set_db -quiet probabilistic_extraction true
set_db -quiet ple_correlation_factors {1.9000 2.0000}
set_db -quiet maximum_interval_of_vias inf
set_db -quiet layer_aware_buffer true
set_db -quiet ple_mode global
set_db -quiet wireload_selection none
set_db -quiet operating_condition:default_emulate_libset_max/slow_vdd1v0/PVT_0P9V_125C .tree_type balanced_tree
set_db -quiet operating_condition:default_emulate_libset_max/slow_vdd1v0/_nominal_ .tree_type balanced_tree
set_db -quiet operating_condition:default_emulate_libset_max/fast_vdd1v2/PVT_1P32V_0C .tree_type balanced_tree
set_db -quiet operating_condition:default_emulate_libset_max/fast_vdd1v2/_nominal_ .tree_type balanced_tree
# BEGIN MSV SECTION
# END MSV SECTION
define_clock -name CLK -domain domain_1 -period 5000.0 -divide_period 1 -rise 0 -divide_rise 1 -fall 2 -divide_fall 5 -remove -design design:top port:top/SYS_CLOCK
define_cost_group -design design:top -name C2C
define_cost_group -design design:top -name C2O
define_cost_group -design design:top -name CLK
define_cost_group -design design:top -name I2C
define_cost_group -design design:top -name I2O
external_delay -accumulate -input {0.0 no_value 0.0 no_value} -clock clock:top/CLK -name create_clock_delay_domain_1_CLK_R_0 port:top/SYS_CLOCK
set_db -quiet external_delay:top/create_clock_delay_domain_1_CLK_R_0 .clock_network_latency_included true
external_delay -accumulate -input {no_value 0.0 no_value 0.0} -clock clock:top/CLK -edge_fall -name create_clock_delay_domain_1_CLK_F_0 port:top/SYS_CLOCK
set_db -quiet external_delay:top/create_clock_delay_domain_1_CLK_F_0 .clock_network_latency_included true
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8 port:top/SRST
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_1_1 {{port:top/X0[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_2_1 {{port:top/X0[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_3_1 {{port:top/X0[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_4_1 {{port:top/X0[0]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_5_1 {{port:top/X1[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_6_1 {{port:top/X1[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_7_1 {{port:top/X1[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_8_1 {{port:top/X1[0]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_9_1 {{port:top/X2[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_10_1 {{port:top/X2[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_11_1 {{port:top/X2[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_12_1 {{port:top/X2[0]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_13_1 {{port:top/X3[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_14_1 {{port:top/X3[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_15_1 {{port:top/X3[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_16_1 {{port:top/X3[0]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_17_1 {{port:top/C0[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_18_1 {{port:top/C0[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_19_1 {{port:top/C0[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_20_1 {{port:top/C0[0]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_21_1 {{port:top/C1[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_22_1 {{port:top/C1[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_23_1 {{port:top/C1[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_24_1 {{port:top/C1[0]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_25_1 {{port:top/C2[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_26_1 {{port:top/C2[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_27_1 {{port:top/C2[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_28_1 {{port:top/C2[0]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_29_1 {{port:top/C3[3]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_30_1 {{port:top/C3[2]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_31_1 {{port:top/C3[1]}}
external_delay -accumulate -input {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_8_32_1 {{port:top/C3[0]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11 {{port:top/Y[9]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_32_1 {{port:top/Y[8]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_33_1 {{port:top/Y[7]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_34_1 {{port:top/Y[6]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_35_1 {{port:top/Y[5]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_36_1 {{port:top/Y[4]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_37_1 {{port:top/Y[3]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_38_1 {{port:top/Y[2]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_39_1 {{port:top/Y[1]}}
external_delay -accumulate -output {0.0 0.0 0.0 0.0} -clock clock:top/CLK -name top.sdc_line_11_40_1 {{port:top/Y[0]}}
path_group -paths [specify_paths -lenient -to clock:top/CLK]  -name CLK -group cost_group:top/CLK -user_priority -1047552
path_disable -paths [specify_paths -lenient -from port:top/SRST]  -name top.sdc_line_14 -user_priority -770048
set_db -quiet exception:top/top.sdc_line_14 .sdc_filename_linenumber {{design_data/top.sdc 14}}
path_group -paths [specify_paths -lenient -from {{inst:top/Y_reg[9]} {inst:top/Y_reg[8]} {inst:top/Y_reg[6]} {inst:top/Y_reg[2]} {inst:top/Y_reg[1]} {inst:top/Y_reg[5]} {inst:top/Y_reg[0]} {inst:top/Y_reg[7]} {inst:top/Y_reg[4]} {inst:top/Y_reg[3]}} -to {{inst:top/Y_reg[9]} {inst:top/Y_reg[8]} {inst:top/Y_reg[6]} {inst:top/Y_reg[2]} {inst:top/Y_reg[1]} {inst:top/Y_reg[5]} {inst:top/Y_reg[0]} {inst:top/Y_reg[7]} {inst:top/Y_reg[4]} {inst:top/Y_reg[3]}}]  -name C2C -group cost_group:top/C2C
path_group -paths [specify_paths -lenient -from {{inst:top/Y_reg[9]} {inst:top/Y_reg[8]} {inst:top/Y_reg[6]} {inst:top/Y_reg[2]} {inst:top/Y_reg[1]} {inst:top/Y_reg[5]} {inst:top/Y_reg[0]} {inst:top/Y_reg[7]} {inst:top/Y_reg[4]} {inst:top/Y_reg[3]}} -to {{port:top/Y[9]} {port:top/Y[8]} {port:top/Y[7]} {port:top/Y[6]} {port:top/Y[5]} {port:top/Y[4]} {port:top/Y[3]} {port:top/Y[2]} {port:top/Y[1]} {port:top/Y[0]}}]  -name C2O -group cost_group:top/C2O
path_group -paths [specify_paths -lenient -from {port:top/SYS_CLOCK port:top/SRST {port:top/X0[3]} {port:top/X0[2]} {port:top/X0[1]} {port:top/X0[0]} {port:top/X1[3]} {port:top/X1[2]} {port:top/X1[1]} {port:top/X1[0]} {port:top/X2[3]} {port:top/X2[2]} {port:top/X2[1]} {port:top/X2[0]} {port:top/X3[3]} {port:top/X3[2]} {port:top/X3[1]} {port:top/X3[0]} {port:top/C0[3]} {port:top/C0[2]} {port:top/C0[1]} {port:top/C0[0]} {port:top/C1[3]} {port:top/C1[2]} {port:top/C1[1]} {port:top/C1[0]} {port:top/C2[3]} {port:top/C2[2]} {port:top/C2[1]} {port:top/C2[0]} {port:top/C3[3]} {port:top/C3[2]} {port:top/C3[1]} {port:top/C3[0]}} -to {{inst:top/Y_reg[9]} {inst:top/Y_reg[8]} {inst:top/Y_reg[6]} {inst:top/Y_reg[2]} {inst:top/Y_reg[1]} {inst:top/Y_reg[5]} {inst:top/Y_reg[0]} {inst:top/Y_reg[7]} {inst:top/Y_reg[4]} {inst:top/Y_reg[3]}}]  -name I2C -group cost_group:top/I2C
path_group -paths [specify_paths -lenient -from {port:top/SYS_CLOCK port:top/SRST {port:top/X0[3]} {port:top/X0[2]} {port:top/X0[1]} {port:top/X0[0]} {port:top/X1[3]} {port:top/X1[2]} {port:top/X1[1]} {port:top/X1[0]} {port:top/X2[3]} {port:top/X2[2]} {port:top/X2[1]} {port:top/X2[0]} {port:top/X3[3]} {port:top/X3[2]} {port:top/X3[1]} {port:top/X3[0]} {port:top/C0[3]} {port:top/C0[2]} {port:top/C0[1]} {port:top/C0[0]} {port:top/C1[3]} {port:top/C1[2]} {port:top/C1[1]} {port:top/C1[0]} {port:top/C2[3]} {port:top/C2[2]} {port:top/C2[1]} {port:top/C2[0]} {port:top/C3[3]} {port:top/C3[2]} {port:top/C3[1]} {port:top/C3[0]}} -to {{port:top/Y[9]} {port:top/Y[8]} {port:top/Y[7]} {port:top/Y[6]} {port:top/Y[5]} {port:top/Y[4]} {port:top/Y[3]} {port:top/Y[2]} {port:top/Y[1]} {port:top/Y[0]}}]  -name I2O -group cost_group:top/I2O
# BEGIN DFT SECTION
set_db -quiet dft_scan_style muxed_scan
set_db -quiet dft_scanbit_waveform_analysis false
# END DFT SECTION
set_db -quiet design:top .seq_reason_deleted_internal {}
set_db -quiet design:top .qos_by_stage {{to_generic {wns -11111111} {tns -111111111} {vep -111111111} {area 1285} {cell_count 442} {utilization  0.00} {runtime 7 30 6 30} }{first_condense {wns -11111111} {tns -111111111} {vep -111111111} {area 1746} {cell_count 629} {utilization  0.00} {runtime 2 32 2 33} }{second_condense {wns -11111111} {tns -111111111} {vep -111111111} {area 1738} {cell_count 626} {utilization  0.00} {runtime 1 36 2 38} }{reify {wns 2650} {tns 0} {vep 0} {area 455} {cell_count 144} {utilization  0.00} {runtime 11 47 20 58} }{global_incr_map {wns 2312} {tns 0} {vep 0} {area 554} {cell_count 144} {utilization  0.00} {runtime 0 47 0 59} }{incr_opt {wns 214748365} {tns 0} {vep 0} {area 557} {cell_count 144} {utilization  0.00} {runtime 0 53 0 64} }}
set_db -quiet design:top .seq_mbci_coverage 0.0
set_db -quiet design:top .hdl_filelist {{default -sv {SYNTHESIS} {design_data/top.sv} {. ../RTL $DESIGN_DIR} {}}}
set_db -quiet design:top .hdl_user_name top
set_db -quiet design:top .verification_directory fv/top
set_db -quiet design:top .lp_clock_gating_max_flops inf
set_db -quiet port:top/SYS_CLOCK .original_name SYS_CLOCK
set_db -quiet port:top/SRST .original_name SRST
set_db -quiet {port:top/X0[3]} .original_name {X0[3]}
set_db -quiet {port:top/X0[2]} .original_name {X0[2]}
set_db -quiet {port:top/X0[1]} .original_name {X0[1]}
set_db -quiet {port:top/X0[0]} .original_name {X0[0]}
set_db -quiet {port:top/X1[3]} .original_name {X1[3]}
set_db -quiet {port:top/X1[2]} .original_name {X1[2]}
set_db -quiet {port:top/X1[1]} .original_name {X1[1]}
set_db -quiet {port:top/X1[0]} .original_name {X1[0]}
set_db -quiet {port:top/X2[3]} .original_name {X2[3]}
set_db -quiet {port:top/X2[2]} .original_name {X2[2]}
set_db -quiet {port:top/X2[1]} .original_name {X2[1]}
set_db -quiet {port:top/X2[0]} .original_name {X2[0]}
set_db -quiet {port:top/X3[3]} .original_name {X3[3]}
set_db -quiet {port:top/X3[2]} .original_name {X3[2]}
set_db -quiet {port:top/X3[1]} .original_name {X3[1]}
set_db -quiet {port:top/X3[0]} .original_name {X3[0]}
set_db -quiet {port:top/C0[3]} .original_name {C0[3]}
set_db -quiet {port:top/C0[2]} .original_name {C0[2]}
set_db -quiet {port:top/C0[1]} .original_name {C0[1]}
set_db -quiet {port:top/C0[0]} .original_name {C0[0]}
set_db -quiet {port:top/C1[3]} .original_name {C1[3]}
set_db -quiet {port:top/C1[2]} .original_name {C1[2]}
set_db -quiet {port:top/C1[1]} .original_name {C1[1]}
set_db -quiet {port:top/C1[0]} .original_name {C1[0]}
set_db -quiet {port:top/C2[3]} .original_name {C2[3]}
set_db -quiet {port:top/C2[2]} .original_name {C2[2]}
set_db -quiet {port:top/C2[1]} .original_name {C2[1]}
set_db -quiet {port:top/C2[0]} .original_name {C2[0]}
set_db -quiet {port:top/C3[3]} .original_name {C3[3]}
set_db -quiet {port:top/C3[2]} .original_name {C3[2]}
set_db -quiet {port:top/C3[1]} .original_name {C3[1]}
set_db -quiet {port:top/C3[0]} .original_name {C3[0]}
set_db -quiet {port:top/Y[9]} .original_name {Y[9]}
set_db -quiet {port:top/Y[8]} .original_name {Y[8]}
set_db -quiet {port:top/Y[7]} .original_name {Y[7]}
set_db -quiet {port:top/Y[6]} .original_name {Y[6]}
set_db -quiet {port:top/Y[5]} .original_name {Y[5]}
set_db -quiet {port:top/Y[4]} .original_name {Y[4]}
set_db -quiet {port:top/Y[3]} .original_name {Y[3]}
set_db -quiet {port:top/Y[2]} .original_name {Y[2]}
set_db -quiet {port:top/Y[1]} .original_name {Y[1]}
set_db -quiet {port:top/Y[0]} .original_name {Y[0]}
set_db -quiet {inst:top/Y_reg[9]} .original_name {{Y[9]}}
set_db -quiet {inst:top/Y_reg[9]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[9]} .single_bit_orig_name {Y[9]}
set_db -quiet {inst:top/Y_reg[9]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[9]/Q} .original_name {Y[9]/q}
set_db -quiet {inst:top/Y_reg[8]} .original_name {{Y[8]}}
set_db -quiet {inst:top/Y_reg[8]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[8]} .single_bit_orig_name {Y[8]}
set_db -quiet {inst:top/Y_reg[8]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[8]/Q} .original_name {Y[8]/q}
set_db -quiet {inst:top/Y_reg[6]} .original_name {{Y[6]}}
set_db -quiet {inst:top/Y_reg[6]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[6]} .single_bit_orig_name {Y[6]}
set_db -quiet {inst:top/Y_reg[6]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[6]/Q} .original_name {Y[6]/q}
set_db -quiet {inst:top/Y_reg[2]} .original_name {{Y[2]}}
set_db -quiet {inst:top/Y_reg[2]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[2]} .single_bit_orig_name {Y[2]}
set_db -quiet {inst:top/Y_reg[2]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[2]/Q} .original_name {Y[2]/q}
set_db -quiet {inst:top/Y_reg[1]} .original_name {{Y[1]}}
set_db -quiet {inst:top/Y_reg[1]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[1]} .single_bit_orig_name {Y[1]}
set_db -quiet {inst:top/Y_reg[1]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[1]/Q} .original_name {Y[1]/q}
set_db -quiet {inst:top/Y_reg[5]} .original_name {{Y[5]}}
set_db -quiet {inst:top/Y_reg[5]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[5]} .single_bit_orig_name {Y[5]}
set_db -quiet {inst:top/Y_reg[5]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[5]/Q} .original_name {Y[5]/q}
set_db -quiet {inst:top/Y_reg[0]} .original_name {{Y[0]}}
set_db -quiet {inst:top/Y_reg[0]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[0]} .single_bit_orig_name {Y[0]}
set_db -quiet {inst:top/Y_reg[0]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[0]/Q} .original_name {Y[0]/q}
set_db -quiet {inst:top/Y_reg[7]} .original_name {{Y[7]}}
set_db -quiet {inst:top/Y_reg[7]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[7]} .single_bit_orig_name {Y[7]}
set_db -quiet {inst:top/Y_reg[7]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[7]/Q} .original_name {Y[7]/q}
set_db -quiet {inst:top/Y_reg[4]} .original_name {{Y[4]}}
set_db -quiet {inst:top/Y_reg[4]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[4]} .single_bit_orig_name {Y[4]}
set_db -quiet {inst:top/Y_reg[4]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[4]/Q} .original_name {Y[4]/q}
set_db -quiet {inst:top/Y_reg[3]} .original_name {{Y[3]}}
set_db -quiet {inst:top/Y_reg[3]} .orig_hdl_instantiated false
set_db -quiet {inst:top/Y_reg[3]} .single_bit_orig_name {Y[3]}
set_db -quiet {inst:top/Y_reg[3]} .gint_phase_inversion false
set_db -quiet {pin:top/Y_reg[3]/Q} .original_name {Y[3]/q}
# BEGIN PMBIST SECTION
# END PMBIST SECTION
# BEGIN PHYSICAL ANNOTATION SECTION
# END PHYSICAL ANNOTATION SECTION
set_db -quiet source_verbose true
#############################################################
#####   FLOW WRITE   ########################################
##
## Written by Genus(TM) Synthesis Solution version 21.18-s082_1
## flowkit v21.12-s019_1
## Written on 11:06:31 02-May 2026
#############################################################
#####   Flow Definitions   ##################################

#############################################################
#####   Step Definitions   ##################################


#############################################################
#####   Attribute Definitions   #############################

if {[is_attribute flow_edit_end_steps -obj_type root]} {set_db flow_edit_end_steps {}}
if {[is_attribute flow_edit_start_steps -obj_type root]} {set_db flow_edit_start_steps {}}
if {[is_attribute flow_footer_tcl -obj_type root]} {set_db flow_footer_tcl {}}
if {[is_attribute flow_header_tcl -obj_type root]} {set_db flow_header_tcl {}}
if {[is_attribute flow_metadata -obj_type root]} {set_db flow_metadata {}}
if {[is_attribute flow_setup_config -obj_type root]} {set_db flow_setup_config {HUDDLE {!!map {}}}}
if {[is_attribute flow_step_begin_tcl -obj_type root]} {set_db flow_step_begin_tcl {}}
if {[is_attribute flow_step_check_tcl -obj_type root]} {set_db flow_step_check_tcl {}}
if {[is_attribute flow_step_end_tcl -obj_type root]} {set_db flow_step_end_tcl {}}
if {[is_attribute flow_step_order -obj_type root]} {set_db flow_step_order {}}
if {[is_attribute flow_summary_tcl -obj_type root]} {set_db flow_summary_tcl {}}
if {[is_attribute flow_template_feature_definition -obj_type root]} {set_db flow_template_feature_definition {}}
if {[is_attribute flow_template_type -obj_type root]} {set_db flow_template_type {}}
if {[is_attribute flow_template_tools -obj_type root]} {set_db flow_template_tools {}}
if {[is_attribute flow_template_version -obj_type root]} {set_db flow_template_version {}}
if {[is_attribute flow_user_templates -obj_type root]} {set_db flow_user_templates {}}


#############################################################
#####   Flow History   ######################################

if {[is_attribute flow_user_templates -obj_type root]} {set_db flow_user_templates {}}
if {[is_attribute flow_plugin_steps -obj_type root]} {set_db flow_plugin_steps {}}
if {[is_attribute flow_template_type -obj_type root]} {set_db flow_template_type {}}
if {[is_attribute flow_template_tools -obj_type root]} {set_db flow_template_tools {}}
if {[is_attribute flow_template_version -obj_type root]} {set_db flow_template_version {}}
if {[is_attribute flow_template_feature_definition -obj_type root]} {set_db flow_template_feature_definition {}}
if {[is_attribute flow_remark -obj_type root]} {set_db flow_remark {}}
if {[is_attribute flow_features -obj_type root]} {set_db flow_features {}}
if {[is_attribute flow_feature_values -obj_type root]} {set_db flow_feature_values {}}
if {[is_attribute flow_write_db_args -obj_type root]} {set_db flow_write_db_args {}}
if {[is_attribute flow_write_db_sdc -obj_type root]} {set_db flow_write_db_sdc true}
if {[is_attribute flow_write_db_common -obj_type root]} {set_db flow_write_db_common false}
if {[is_attribute flow_post_db_overwrite -obj_type root]} {set_db flow_post_db_overwrite {}}
if {[is_attribute flow_step_order -obj_type root]} {set_db flow_step_order {}}
if {[is_attribute flow_step_begin_tcl -obj_type root]} {set_db flow_step_begin_tcl {}}
if {[is_attribute flow_step_end_tcl -obj_type root]} {set_db flow_step_end_tcl {}}
if {[is_attribute flow_step_last -obj_type root]} {set_db flow_step_last {}}
if {[is_attribute flow_step_current -obj_type root]} {set_db flow_step_current {}}
if {[is_attribute flow_step_canonical_current -obj_type root]} {set_db flow_step_canonical_current {}}
if {[is_attribute flow_step_next -obj_type root]} {set_db flow_step_next {}}
if {[is_attribute flow_working_directory -obj_type root]} {set_db flow_working_directory .}
if {[is_attribute flow_branch -obj_type root]} {set_db flow_branch {}}
if {[is_attribute flow_caller_data -obj_type root]} {set_db flow_caller_data {}}
if {[is_attribute flow_metrics_snapshot_uuid -obj_type root]} {set_db flow_metrics_snapshot_uuid 28dad1a7-6d91-4ac7-957b-557f523d4253}
if {[is_attribute flow_starting_db -obj_type root]} {set_db flow_starting_db {}}
if {[is_attribute flow_db_directory -obj_type root]} {set_db flow_db_directory dbs}
if {[is_attribute flow_report_directory -obj_type root]} {set_db flow_report_directory reports}
if {[is_attribute flow_log_directory -obj_type root]} {set_db flow_log_directory logs}
if {[is_attribute flow_mail_to -obj_type root]} {set_db flow_mail_to {}}
if {[is_attribute flow_exit_when_done -obj_type root]} {set_db flow_exit_when_done false}
if {[is_attribute flow_mail_on_error -obj_type root]} {set_db flow_mail_on_error false}
if {[is_attribute flow_summary_tcl -obj_type root]} {set_db flow_summary_tcl {}}
if {[is_attribute flow_history -obj_type root]} {set_db flow_history {}}
if {[is_attribute flow_step_last_status -obj_type root]} {set_db flow_step_last_status not_run}
if {[is_attribute flow_step_last_msg -obj_type root]} {set_db flow_step_last_msg {}}
if {[is_attribute flow_run_tag -obj_type root]} {set_db flow_run_tag {}}
if {[is_attribute flow_current_cache -obj_type root]} {set_db flow_current_cache {}}
if {[is_attribute flow_step_order_cache -obj_type root]} {set_db flow_step_order_cache {}}
if {[is_attribute flow_step_results_cache -obj_type root]} {set_db flow_step_results_cache {}}
if {[is_attribute flow_metadata -obj_type root]} {set_db flow_metadata {}}
if {[is_attribute flow_execute_in_global -obj_type root]} {set_db flow_execute_in_global true}
if {[is_attribute flow_overwrite_db -obj_type root]} {set_db flow_overwrite_db false}
if {[is_attribute flow_print_run_information -obj_type root]} {set_db flow_print_run_information false}
if {[is_attribute flow_verbose -obj_type root]} {set_db flow_verbose true}
if {[is_attribute flow_print_run_information_full -obj_type root]} {set_db flow_print_run_information_full false}
if {[is_attribute flow_header_tcl -obj_type root]} {set_db flow_header_tcl {}}
if {[is_attribute flow_footer_tcl -obj_type root]} {set_db flow_footer_tcl {}}
if {[is_attribute flow_init_header_tcl -obj_type root]} {set_db flow_init_header_tcl {}}
if {[is_attribute flow_init_footer_tcl -obj_type root]} {set_db flow_init_footer_tcl {}}
if {[is_attribute flow_edit_start_steps -obj_type root]} {set_db flow_edit_start_steps {}}
if {[is_attribute flow_edit_end_steps -obj_type root]} {set_db flow_edit_end_steps {}}
if {[is_attribute flow_step_last_number -obj_type root]} {set_db flow_step_last_number 0}
if {[is_attribute flow_autoload_applets -obj_type root]} {set_db flow_autoload_applets false}
if {[is_attribute flow_autoload_dir -obj_type root]} {set_db flow_autoload_dir error}
if {[is_attribute flow_skip_auto_db_save -obj_type root]} {set_db flow_skip_auto_db_save true}
if {[is_attribute flow_skip_auto_generate_metrics -obj_type root]} {set_db flow_skip_auto_generate_metrics false}
if {[is_attribute flow_top -obj_type root]} {set_db flow_top {}}
if {[is_attribute flow_hier_path -obj_type root]} {set_db flow_hier_path {}}
if {[is_attribute flow_schedule -obj_type root]} {set_db flow_schedule {}}
if {[is_attribute flow_step_check_tcl -obj_type root]} {set_db flow_step_check_tcl {}}
if {[is_attribute flow_script -obj_type root]} {set_db flow_script {}}
if {[is_attribute flow_yaml_script -obj_type root]} {set_db flow_yaml_script {}}
if {[is_attribute flow_cla_enabled_features -obj_type root]} {set_db flow_cla_enabled_features {}}
if {[is_attribute flow_cla_inject_tcl -obj_type root]} {set_db flow_cla_inject_tcl {}}
if {[is_attribute flow_error_message -obj_type root]} {set_db flow_error_message {}}
if {[is_attribute flow_error_errorinfo -obj_type root]} {set_db flow_error_errorinfo {}}
if {[is_attribute flow_exclude_time_for_init_flow -obj_type root]} {set_db flow_exclude_time_for_init_flow false}
if {[is_attribute flow_error_write_db -obj_type root]} {set_db flow_error_write_db true}
if {[is_attribute flow_advanced_metric_isolation -obj_type root]} {set_db flow_advanced_metric_isolation flow}
if {[is_attribute flow_yaml_root -obj_type root]} {set_db flow_yaml_root {}}
if {[is_attribute flow_yaml_root_dir -obj_type root]} {set_db flow_yaml_root_dir {}}
if {[is_attribute flow_setup_config -obj_type root]} {set_db flow_setup_config {HUDDLE {!!map {}}}}

#############################################################
#####   User Defined Attributes   ###########################

