
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jun 22 2026 19:49:00 +06 (Jun 22 2026 13:49:00 UTC)

// Verification Directory fv/RISC_V3 

module RISC_V3(SYS_CLOCK, RST, DM_IN, PC, DM_ADDR, DM_WR, IR, ACCUM_R,
     PSTATE);
  input SYS_CLOCK, RST;
  output [31:0] DM_IN, IR, ACCUM_R;
  output [3:0] PC, DM_ADDR;
  output DM_WR;
  output [2:0] PSTATE;
  wire SYS_CLOCK, RST;
  wire [31:0] DM_IN, IR, ACCUM_R;
  wire [3:0] PC, DM_ADDR;
  wire DM_WR;
  wire [2:0] PSTATE;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_20;
  wire n_21, n_22, n_23, n_24, n_28;
  assign PSTATE[2] = 1'b0;
  assign ACCUM_R[0] = 1'b0;
  assign ACCUM_R[1] = 1'b0;
  assign ACCUM_R[2] = 1'b0;
  assign ACCUM_R[3] = 1'b0;
  assign ACCUM_R[4] = 1'b0;
  assign ACCUM_R[5] = 1'b0;
  assign ACCUM_R[6] = 1'b0;
  assign ACCUM_R[7] = 1'b0;
  assign ACCUM_R[8] = 1'b0;
  assign ACCUM_R[9] = 1'b0;
  assign ACCUM_R[10] = 1'b0;
  assign ACCUM_R[11] = 1'b0;
  assign ACCUM_R[12] = 1'b0;
  assign ACCUM_R[13] = 1'b0;
  assign ACCUM_R[14] = 1'b0;
  assign ACCUM_R[15] = 1'b0;
  assign ACCUM_R[16] = 1'b0;
  assign ACCUM_R[17] = 1'b0;
  assign ACCUM_R[18] = 1'b0;
  assign ACCUM_R[19] = 1'b0;
  assign ACCUM_R[20] = 1'b0;
  assign ACCUM_R[21] = 1'b0;
  assign ACCUM_R[22] = 1'b0;
  assign ACCUM_R[23] = 1'b0;
  assign ACCUM_R[24] = 1'b0;
  assign ACCUM_R[25] = 1'b0;
  assign ACCUM_R[26] = 1'b0;
  assign ACCUM_R[27] = 1'b0;
  assign ACCUM_R[28] = 1'b0;
  assign ACCUM_R[29] = 1'b0;
  assign ACCUM_R[30] = 1'b0;
  assign ACCUM_R[31] = 1'b0;
  assign IR[0] = 1'b0;
  assign IR[1] = 1'b0;
  assign IR[2] = 1'b0;
  assign IR[3] = 1'b0;
  assign IR[4] = 1'b0;
  assign IR[5] = 1'b0;
  assign IR[6] = 1'b0;
  assign IR[7] = 1'b0;
  assign IR[8] = 1'b0;
  assign IR[9] = 1'b0;
  assign IR[10] = 1'b0;
  assign IR[11] = 1'b0;
  assign IR[12] = 1'b0;
  assign IR[13] = 1'b0;
  assign IR[14] = 1'b0;
  assign IR[15] = 1'b0;
  assign IR[16] = 1'b0;
  assign IR[17] = 1'b0;
  assign IR[18] = 1'b0;
  assign IR[19] = 1'b0;
  assign IR[20] = 1'b0;
  assign IR[21] = 1'b0;
  assign IR[22] = 1'b0;
  assign IR[23] = 1'b0;
  assign IR[24] = 1'b0;
  assign IR[25] = 1'b0;
  assign IR[26] = 1'b0;
  assign IR[27] = 1'b0;
  assign IR[28] = 1'b0;
  assign IR[29] = 1'b0;
  assign IR[30] = 1'b0;
  assign IR[31] = 1'b0;
  assign DM_WR = 1'b0;
  assign DM_ADDR[0] = 1'b0;
  assign DM_ADDR[1] = 1'b0;
  assign DM_ADDR[2] = 1'b0;
  assign DM_ADDR[3] = 1'b0;
  assign DM_IN[0] = 1'b0;
  assign DM_IN[1] = 1'b0;
  assign DM_IN[2] = 1'b0;
  assign DM_IN[3] = 1'b0;
  assign DM_IN[4] = 1'b0;
  assign DM_IN[5] = 1'b0;
  assign DM_IN[6] = 1'b0;
  assign DM_IN[7] = 1'b0;
  assign DM_IN[8] = 1'b0;
  assign DM_IN[9] = 1'b0;
  assign DM_IN[10] = 1'b0;
  assign DM_IN[11] = 1'b0;
  assign DM_IN[12] = 1'b0;
  assign DM_IN[13] = 1'b0;
  assign DM_IN[14] = 1'b0;
  assign DM_IN[15] = 1'b0;
  assign DM_IN[16] = 1'b0;
  assign DM_IN[17] = 1'b0;
  assign DM_IN[18] = 1'b0;
  assign DM_IN[19] = 1'b0;
  assign DM_IN[20] = 1'b0;
  assign DM_IN[21] = 1'b0;
  assign DM_IN[22] = 1'b0;
  assign DM_IN[23] = 1'b0;
  assign DM_IN[24] = 1'b0;
  assign DM_IN[25] = 1'b0;
  assign DM_IN[26] = 1'b0;
  assign DM_IN[27] = 1'b0;
  assign DM_IN[28] = 1'b0;
  assign DM_IN[29] = 1'b0;
  assign DM_IN[30] = 1'b0;
  assign DM_IN[31] = 1'b0;
  DFFX1 \PC1_PC_reg[3] (.CK (SYS_CLOCK), .D (n_24), .Q (PC[3]), .QN
       (UNCONNECTED));
  CLKINVX1 g13951(.A (n_23), .Y (n_24));
  AOI22X1 g13952__2398(.A0 (n_17), .A1 (PC[3]), .B0 (n_28), .B1 (n_16),
       .Y (n_23));
  DFFX1 \PC1_PC_reg[1] (.CK (SYS_CLOCK), .D (n_22), .Q (PC[1]), .QN
       (UNCONNECTED0));
  DFFX1 \PC1_PC_reg[2] (.CK (SYS_CLOCK), .D (n_21), .Q (PC[2]), .QN
       (UNCONNECTED1));
  CLKINVX1 g13955(.A (n_20), .Y (n_22));
  CLKINVX1 g13957(.A (n_18), .Y (n_21));
  AOI22X1 g13956__5107(.A0 (n_12), .A1 (PC[1]), .B0 (n_28), .B1 (n_2),
       .Y (n_20));
  AOI22X1 g13958__6260(.A0 (n_9), .A1 (PC[2]), .B0 (n_28), .B1 (n_5),
       .Y (n_18));
  OAI21X1 g13960__4319(.A0 (n_11), .A1 (n_15), .B0 (n_10), .Y (n_17));
  SDFFX1 \PC1_PC_reg[0] (.CK (SYS_CLOCK), .D (n_28), .SI (n_4), .SE
       (PC[0]), .Q (PC[0]), .QN (UNCONNECTED2));
  DFFX1 \PC1_PSTATE_reg[0] (.CK (SYS_CLOCK), .D (n_13), .Q (PSTATE[0]),
       .QN (UNCONNECTED3));
  NOR2X1 g13963__8428(.A (PC[3]), .B (n_14), .Y (n_16));
  DFFX1 \PC1_PSTATE_reg[1] (.CK (SYS_CLOCK), .D (n_28), .Q (PSTATE[1]),
       .QN (n_0));
  CLKINVX1 g13968(.A (n_14), .Y (n_15));
  NOR2X1 g13969__5526(.A (RST), .B (n_6), .Y (n_13));
  OAI21X1 g13961__6783(.A0 (PC[0]), .A1 (n_11), .B0 (n_10), .Y (n_12));
  OAI21X1 g13962__3680(.A0 (n_7), .A1 (n_11), .B0 (n_10), .Y (n_9));
  NAND2X1 g13971__1705(.A (PC[2]), .B (n_7), .Y (n_14));
  CLKINVX1 g13973(.A (n_11), .Y (n_6));
  NOR2X1 g13970__5122(.A (PC[2]), .B (n_3), .Y (n_5));
  CLKINVX1 g13976(.A (n_10), .Y (n_4));
  CLKINVX1 g13972(.A (n_3), .Y (n_7));
  NOR2X1 g13977__8246(.A (PC[1]), .B (n_1), .Y (n_2));
  NAND2X1 g13975__7098(.A (PSTATE[0]), .B (n_0), .Y (n_11));
  NAND2X1 g13974__6131(.A (PC[1]), .B (PC[0]), .Y (n_3));
  NOR2X1 g13978__1881(.A (RST), .B (PSTATE[1]), .Y (n_10));
  CLKINVX1 g13980(.A (PC[0]), .Y (n_1));
  NOR2X1 g13966__13987(.A (RST), .B (n_11), .Y (n_28));
endmodule

