/*
###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Sat May  2 12:26:21 2026
#  Design:            MAC_4BIT
#  Command:           saveNetlist final/MAC_4BIT.lvs.v -includePowerGround
###############################################################
*/
module DFFX1 (
	Q, 
	QN, 
	CK, 
	D, 
	VSS, 
	VDD);
   output Q;
   output QN;
   input CK;
   input D;
   input VSS;
   input VDD;
endmodule

module NOR2X1 (
	Y, 
	A, 
	B, 
	VSS, 
	VDD);
   output Y;
   input A;
   input B;
   input VSS;
   input VDD;
endmodule

module CLKINVX1 (
	Y, 
	A, 
	VSS, 
	VDD);
   output Y;
   input A;
   input VSS;
   input VDD;
endmodule

module ADDFX1 (
	CO, 
	S, 
	A, 
	B, 
	CI, 
	VSS, 
	VDD);
   output CO;
   output S;
   input A;
   input B;
   input CI;
   input VSS;
   input VDD;
endmodule

module ADDHX1 (
	CO, 
	S, 
	A, 
	B, 
	VSS, 
	VDD);
   output CO;
   output S;
   input A;
   input B;
   input VSS;
   input VDD;
endmodule

module AOI21X1 (
	Y, 
	A0, 
	A1, 
	B0, 
	VSS, 
	VDD);
   output Y;
   input A0;
   input A1;
   input B0;
   input VSS;
   input VDD;
endmodule

module AND2X1 (
	Y, 
	A, 
	B, 
	VSS, 
	VDD);
   output Y;
   input A;
   input B;
   input VSS;
   input VDD;
endmodule

module NAND2X1 (
	Y, 
	A, 
	B, 
	VSS, 
	VDD);
   output Y;
   input A;
   input B;
   input VSS;
   input VDD;
endmodule

module MAC_4BIT (
	SYS_CLOCK, 
	SRST, 
	A, 
	B, 
	Y);
   input SYS_CLOCK;
   input SRST;
   input [3:0] A;
   input [3:0] B;
   output [7:0] Y;

   // Internal wires
   wire VSS;
   wire VDD;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_0;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_1;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_2;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_3;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_4;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_5;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_6;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_7;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_8;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_9;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_10;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_11;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_12;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_13;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_14;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_15;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_16;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_17;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_18;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_19;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_20;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_21;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_22;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_23;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_24;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_26;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_27;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_28;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_29;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_30;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_31;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_32;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_33;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_34;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_35;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_36;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_37;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_38;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_39;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_40;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_41;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_42;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_43;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_44;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_45;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_46;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_47;
   wire WALLACE_CSA_DUMMY_OP_groupi_n_48;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;

   // Module instantiations
   DFFX1 \Y_reg[6]  (
	.Q(Y[6]),
	.QN(UNCONNECTED),
	.CK(SYS_CLOCK),
	.D(n_14), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFX1 \Y_reg[1]  (
	.Q(Y[1]),
	.QN(UNCONNECTED0),
	.CK(SYS_CLOCK),
	.D(n_11), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFX1 \Y_reg[0]  (
	.Q(Y[0]),
	.QN(UNCONNECTED1),
	.CK(SYS_CLOCK),
	.D(n_8), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFX1 \Y_reg[7]  (
	.Q(Y[7]),
	.QN(UNCONNECTED2),
	.CK(SYS_CLOCK),
	.D(n_13), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFX1 \Y_reg[4]  (
	.Q(Y[4]),
	.QN(UNCONNECTED3),
	.CK(SYS_CLOCK),
	.D(n_12), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFX1 \Y_reg[3]  (
	.Q(Y[3]),
	.QN(UNCONNECTED4),
	.CK(SYS_CLOCK),
	.D(n_9), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFX1 \Y_reg[2]  (
	.Q(Y[2]),
	.QN(UNCONNECTED5),
	.CK(SYS_CLOCK),
	.D(n_10), 
	.VSS(VSS), 
	.VDD(VDD));
   DFFX1 \Y_reg[5]  (
	.Q(Y[5]),
	.QN(UNCONNECTED6),
	.CK(SYS_CLOCK),
	.D(n_15), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g22__2398 (
	.Y(n_15),
	.A(SRST),
	.B(n_6), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g23__5107 (
	.Y(n_14),
	.A(SRST),
	.B(n_7), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g24__6260 (
	.Y(n_13),
	.A(SRST),
	.B(n_0), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g25__4319 (
	.Y(n_12),
	.A(SRST),
	.B(n_5), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g26__8428 (
	.Y(n_11),
	.A(SRST),
	.B(n_2), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g27__5526 (
	.Y(n_10),
	.A(SRST),
	.B(n_3), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g28__6783 (
	.Y(n_9),
	.A(SRST),
	.B(n_4), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 g29__3680 (
	.Y(n_8),
	.A(SRST),
	.B(n_1), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g30 (
	.Y(n_7),
	.A(n_26), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g31 (
	.Y(n_6),
	.A(n_27), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g32 (
	.Y(n_5),
	.A(n_28), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g33 (
	.Y(n_4),
	.A(n_29), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g34 (
	.Y(n_3),
	.A(n_30), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g35 (
	.Y(n_2),
	.A(n_31), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g36 (
	.Y(n_1),
	.A(n_32), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKINVX1 g37 (
	.Y(n_0),
	.A(n_25), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd1__1617 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_32),
	.S(n_31),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_23),
	.B(Y[1]),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_24), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd2__2802 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_31),
	.S(n_30),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_45),
	.B(Y[2]),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_32), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd3__1705 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_30),
	.S(n_29),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_46),
	.B(Y[3]),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_31), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd4__5122 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_29),
	.S(n_28),
	.A(Y[4]),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_41),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_30), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd5__8246 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_28),
	.S(n_27),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_47),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_42),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_29), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd6__7098 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_27),
	.S(n_26),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_48),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_43),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_28), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd7__6131 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_26),
	.S(n_25),
	.A(Y[7]),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_44),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_27), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_0__1881 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_39),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_45),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_1),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_22),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_18), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_0__5115 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_38),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_37),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_9),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_10),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_19), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_1__7482 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_33),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_46),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_21),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_37),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_39), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_0__4733 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_36),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_35),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_3),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_16),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_20), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_1__6161 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_47),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_41),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_38),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_35),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_33), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_0__9315 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_40),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_34),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_8),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_11),
	.CI(WALLACE_CSA_DUMMY_OP_groupi_n_17), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_1__9945 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_48),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_42),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_36),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_34),
	.CI(Y[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDFX1 WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_006_0__2883 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_44),
	.S(WALLACE_CSA_DUMMY_OP_groupi_n_43),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_2),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_40),
	.CI(Y[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   ADDHX1 WALLACE_CSA_DUMMY_OP_groupi_g137__2346 (
	.CO(WALLACE_CSA_DUMMY_OP_groupi_n_24),
	.S(n_32),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_0),
	.B(Y[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g138__1666 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_23),
	.A0(WALLACE_CSA_DUMMY_OP_groupi_n_12),
	.A1(WALLACE_CSA_DUMMY_OP_groupi_n_5),
	.B0(WALLACE_CSA_DUMMY_OP_groupi_n_18), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g139__7410 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_22),
	.A0(WALLACE_CSA_DUMMY_OP_groupi_n_15),
	.A1(WALLACE_CSA_DUMMY_OP_groupi_n_14),
	.B0(WALLACE_CSA_DUMMY_OP_groupi_n_19), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g140__6417 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_21),
	.A0(WALLACE_CSA_DUMMY_OP_groupi_n_4),
	.A1(WALLACE_CSA_DUMMY_OP_groupi_n_13),
	.B0(WALLACE_CSA_DUMMY_OP_groupi_n_16), 
	.VSS(VSS), 
	.VDD(VDD));
   AOI21X1 WALLACE_CSA_DUMMY_OP_groupi_g141__5477 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_20),
	.A0(WALLACE_CSA_DUMMY_OP_groupi_n_6),
	.A1(WALLACE_CSA_DUMMY_OP_groupi_n_7),
	.B0(WALLACE_CSA_DUMMY_OP_groupi_n_17), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g142__2398 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_19),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_15),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_14), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g143__5107 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_18),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_12),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_5), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g144__6260 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_17),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_6),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_7), 
	.VSS(VSS), 
	.VDD(VDD));
   NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g145__4319 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_16),
	.A(WALLACE_CSA_DUMMY_OP_groupi_n_4),
	.B(WALLACE_CSA_DUMMY_OP_groupi_n_13), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g146__8428 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_11),
	.A(A[2]),
	.B(B[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g147__5526 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_10),
	.A(A[2]),
	.B(B[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g148__6783 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_9),
	.A(A[1]),
	.B(B[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g149__3680 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_8),
	.A(A[3]),
	.B(B[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g150__1617 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_15),
	.A(B[2]),
	.B(A[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g151__2802 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_14),
	.A(B[0]),
	.B(A[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g152__1705 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_13),
	.A(B[0]),
	.B(A[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g153__5122 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_12),
	.A(B[1]),
	.B(A[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g154__8246 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_3),
	.A(A[2]),
	.B(B[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g155__7098 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_2),
	.A(A[3]),
	.B(B[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g156__6131 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_1),
	.A(A[1]),
	.B(B[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g157__1881 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_7),
	.A(B[1]),
	.B(A[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g158__5115 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_0),
	.A(A[0]),
	.B(B[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g159__7482 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_6),
	.A(B[3]),
	.B(A[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g160__4733 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_5),
	.A(B[0]),
	.B(A[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2X1 WALLACE_CSA_DUMMY_OP_groupi_g161__6161 (
	.Y(WALLACE_CSA_DUMMY_OP_groupi_n_4),
	.A(B[3]),
	.B(A[0]), 
	.VSS(VSS), 
	.VDD(VDD));
endmodule

