
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  2 2026 10:34:01 +06 (May  2 2026 04:34:01 UTC)

// Verification Directory fv/top 

module top(SYS_CLOCK, SRST, X0, X1, X2, X3, C0, C1, C2, C3, Y);
  input SYS_CLOCK, SRST;
  input [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  output [9:0] Y;
  wire SYS_CLOCK, SRST;
  wire [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  wire [9:0] Y;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6,
       WALLACE_CSA_DUMMY_OP_groupi_n_7, WALLACE_CSA_DUMMY_OP_groupi_n_8;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15,
       WALLACE_CSA_DUMMY_OP_groupi_n_16;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23,
       WALLACE_CSA_DUMMY_OP_groupi_n_24;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_32;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_48;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55,
       WALLACE_CSA_DUMMY_OP_groupi_n_56;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_57,
       WALLACE_CSA_DUMMY_OP_groupi_n_58,
       WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63,
       WALLACE_CSA_DUMMY_OP_groupi_n_64;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66,
       WALLACE_CSA_DUMMY_OP_groupi_n_67,
       WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71,
       WALLACE_CSA_DUMMY_OP_groupi_n_72;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74,
       WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_76,
       WALLACE_CSA_DUMMY_OP_groupi_n_77,
       WALLACE_CSA_DUMMY_OP_groupi_n_79,
       WALLACE_CSA_DUMMY_OP_groupi_n_80,
       WALLACE_CSA_DUMMY_OP_groupi_n_83;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_84,
       WALLACE_CSA_DUMMY_OP_groupi_n_85,
       WALLACE_CSA_DUMMY_OP_groupi_n_86,
       WALLACE_CSA_DUMMY_OP_groupi_n_87,
       WALLACE_CSA_DUMMY_OP_groupi_n_88,
       WALLACE_CSA_DUMMY_OP_groupi_n_89,
       WALLACE_CSA_DUMMY_OP_groupi_n_90,
       WALLACE_CSA_DUMMY_OP_groupi_n_91;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_92,
       WALLACE_CSA_DUMMY_OP_groupi_n_93,
       WALLACE_CSA_DUMMY_OP_groupi_n_94,
       WALLACE_CSA_DUMMY_OP_groupi_n_95,
       WALLACE_CSA_DUMMY_OP_groupi_n_96,
       WALLACE_CSA_DUMMY_OP_groupi_n_97,
       WALLACE_CSA_DUMMY_OP_groupi_n_98,
       WALLACE_CSA_DUMMY_OP_groupi_n_99;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_100,
       WALLACE_CSA_DUMMY_OP_groupi_n_101,
       WALLACE_CSA_DUMMY_OP_groupi_n_104,
       WALLACE_CSA_DUMMY_OP_groupi_n_106,
       WALLACE_CSA_DUMMY_OP_groupi_n_108,
       WALLACE_CSA_DUMMY_OP_groupi_n_109,
       WALLACE_CSA_DUMMY_OP_groupi_n_112,
       WALLACE_CSA_DUMMY_OP_groupi_n_113;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_114,
       WALLACE_CSA_DUMMY_OP_groupi_n_115,
       WALLACE_CSA_DUMMY_OP_groupi_n_116,
       WALLACE_CSA_DUMMY_OP_groupi_n_117,
       WALLACE_CSA_DUMMY_OP_groupi_n_118,
       WALLACE_CSA_DUMMY_OP_groupi_n_119,
       WALLACE_CSA_DUMMY_OP_groupi_n_120,
       WALLACE_CSA_DUMMY_OP_groupi_n_121;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_122,
       WALLACE_CSA_DUMMY_OP_groupi_n_123,
       WALLACE_CSA_DUMMY_OP_groupi_n_124,
       WALLACE_CSA_DUMMY_OP_groupi_n_125,
       WALLACE_CSA_DUMMY_OP_groupi_n_126,
       WALLACE_CSA_DUMMY_OP_groupi_n_127,
       WALLACE_CSA_DUMMY_OP_groupi_n_128,
       WALLACE_CSA_DUMMY_OP_groupi_n_129;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_130,
       WALLACE_CSA_DUMMY_OP_groupi_n_131,
       WALLACE_CSA_DUMMY_OP_groupi_n_132,
       WALLACE_CSA_DUMMY_OP_groupi_n_133,
       WALLACE_CSA_DUMMY_OP_groupi_n_134,
       WALLACE_CSA_DUMMY_OP_groupi_n_135,
       WALLACE_CSA_DUMMY_OP_groupi_n_136,
       WALLACE_CSA_DUMMY_OP_groupi_n_137;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_138,
       WALLACE_CSA_DUMMY_OP_groupi_n_139,
       WALLACE_CSA_DUMMY_OP_groupi_n_140,
       WALLACE_CSA_DUMMY_OP_groupi_n_141,
       WALLACE_CSA_DUMMY_OP_groupi_n_142,
       WALLACE_CSA_DUMMY_OP_groupi_n_143,
       WALLACE_CSA_DUMMY_OP_groupi_n_144,
       WALLACE_CSA_DUMMY_OP_groupi_n_145;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_146,
       WALLACE_CSA_DUMMY_OP_groupi_n_147,
       WALLACE_CSA_DUMMY_OP_groupi_n_148,
       WALLACE_CSA_DUMMY_OP_groupi_n_149,
       WALLACE_CSA_DUMMY_OP_groupi_n_150,
       WALLACE_CSA_DUMMY_OP_groupi_n_151,
       WALLACE_CSA_DUMMY_OP_groupi_n_152,
       WALLACE_CSA_DUMMY_OP_groupi_n_153;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_154,
       WALLACE_CSA_DUMMY_OP_groupi_n_155,
       WALLACE_CSA_DUMMY_OP_groupi_n_156,
       WALLACE_CSA_DUMMY_OP_groupi_n_157,
       WALLACE_CSA_DUMMY_OP_groupi_n_158,
       WALLACE_CSA_DUMMY_OP_groupi_n_159,
       WALLACE_CSA_DUMMY_OP_groupi_n_160,
       WALLACE_CSA_DUMMY_OP_groupi_n_161;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_162,
       WALLACE_CSA_DUMMY_OP_groupi_n_163,
       WALLACE_CSA_DUMMY_OP_groupi_n_164,
       WALLACE_CSA_DUMMY_OP_groupi_n_165,
       WALLACE_CSA_DUMMY_OP_groupi_n_166,
       WALLACE_CSA_DUMMY_OP_groupi_n_167,
       WALLACE_CSA_DUMMY_OP_groupi_n_168,
       WALLACE_CSA_DUMMY_OP_groupi_n_169;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_170,
       WALLACE_CSA_DUMMY_OP_groupi_n_171,
       WALLACE_CSA_DUMMY_OP_groupi_n_172,
       WALLACE_CSA_DUMMY_OP_groupi_n_173,
       WALLACE_CSA_DUMMY_OP_groupi_n_174,
       WALLACE_CSA_DUMMY_OP_groupi_n_175,
       WALLACE_CSA_DUMMY_OP_groupi_n_176,
       WALLACE_CSA_DUMMY_OP_groupi_n_177;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_178,
       WALLACE_CSA_DUMMY_OP_groupi_n_179,
       WALLACE_CSA_DUMMY_OP_groupi_n_180,
       WALLACE_CSA_DUMMY_OP_groupi_n_181,
       WALLACE_CSA_DUMMY_OP_groupi_n_182,
       WALLACE_CSA_DUMMY_OP_groupi_n_183,
       WALLACE_CSA_DUMMY_OP_groupi_n_184,
       WALLACE_CSA_DUMMY_OP_groupi_n_185;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_186,
       WALLACE_CSA_DUMMY_OP_groupi_n_187,
       WALLACE_CSA_DUMMY_OP_groupi_n_188,
       WALLACE_CSA_DUMMY_OP_groupi_n_189,
       WALLACE_CSA_DUMMY_OP_groupi_n_190,
       WALLACE_CSA_DUMMY_OP_groupi_n_191,
       WALLACE_CSA_DUMMY_OP_groupi_n_192,
       WALLACE_CSA_DUMMY_OP_groupi_n_193;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_194,
       WALLACE_CSA_DUMMY_OP_groupi_n_195,
       WALLACE_CSA_DUMMY_OP_groupi_n_196,
       WALLACE_CSA_DUMMY_OP_groupi_n_197,
       WALLACE_CSA_DUMMY_OP_groupi_n_198,
       WALLACE_CSA_DUMMY_OP_groupi_n_199,
       WALLACE_CSA_DUMMY_OP_groupi_n_200,
       WALLACE_CSA_DUMMY_OP_groupi_n_201;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_202,
       WALLACE_CSA_DUMMY_OP_groupi_n_203, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52;
  DFFHQX1HVT \Y_reg[9] (.CK (SYS_CLOCK), .D (n_7), .Q (Y[9]));
  DFFQX1HVT \Y_reg[8] (.CK (SYS_CLOCK), .D (n_9), .Q (Y[8]));
  DFFQX1HVT \Y_reg[6] (.CK (SYS_CLOCK), .D (n_6), .Q (Y[6]));
  DFFQX1HVT \Y_reg[2] (.CK (SYS_CLOCK), .D (n_4), .Q (Y[2]));
  DFFQX1HVT \Y_reg[1] (.CK (SYS_CLOCK), .D (n_1), .Q (Y[1]));
  DFFQX1HVT \Y_reg[5] (.CK (SYS_CLOCK), .D (n_5), .Q (Y[5]));
  DFFQX1HVT \Y_reg[0] (.CK (SYS_CLOCK), .D (n_0), .Q (Y[0]));
  DFFQX1HVT \Y_reg[7] (.CK (SYS_CLOCK), .D (n_10), .Q (Y[7]));
  DFFQX1HVT \Y_reg[4] (.CK (SYS_CLOCK), .D (n_2), .Q (Y[4]));
  DFFQX1HVT \Y_reg[3] (.CK (SYS_CLOCK), .D (n_3), .Q (Y[3]));
  AND2X1HVT g37__2398(.A (n_46), .B (n_8), .Y (n_10));
  AND2X1HVT g39__5107(.A (n_45), .B (n_8), .Y (n_9));
  AND2X1HVT g38__6260(.A (n_44), .B (n_8), .Y (n_7));
  AND2X1HVT g40__4319(.A (n_47), .B (n_8), .Y (n_6));
  NOR2BX1HVT g41__8428(.AN (n_48), .B (SRST), .Y (n_5));
  AND2X1HVT g42__5526(.A (n_51), .B (n_8), .Y (n_4));
  AND2X1HVT g43__6783(.A (n_50), .B (n_8), .Y (n_3));
  AND2X1HVT g44__3680(.A (n_49), .B (n_8), .Y (n_2));
  AND2X1HVT g45__1617(.A (n_52), .B (n_8), .Y (n_1));
  AND2X1HVT g46__2802(.A (WALLACE_CSA_DUMMY_OP_groupi_n_76), .B (n_8),
       .Y (n_0));
  CLKINVX4HVT g47(.A (SRST), .Y (n_8));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_000_0__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_186), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_187));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_001_0__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_185), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_196));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_001_1__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_184), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_183));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_001_2__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_186), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_183), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_151), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_188));
  ADDFHX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_0__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_182), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_181));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_1__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_179));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_2__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_177));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_3__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_175));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_4__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_185), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_184), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_149));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_5__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_181), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_175), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_179), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_197));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_002_6__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_177), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_149), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_151), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_189));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_0__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_173));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_1__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_171));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_2__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_169));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_3__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_167));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_4__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_165));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_5__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_182), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_147), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_145));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_6__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_169), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_173), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_143));
  ADDFHX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_7__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_171), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_167), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_165), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_141));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_8__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_145), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_129), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_198));
  ADDFHX2HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_003_9__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_141), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_143), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_199), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_190));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_0__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_163));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_1__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_161));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_2__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_159));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_3__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_157));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_4__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_139));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_5__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_159), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_161), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_137));
  ADDFHX2HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_6__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_163), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_147), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_127));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_7__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_157), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_139), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_125));
  ADDFHX2HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_8__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_137), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_127), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_117), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_116));
  ADDFHX2HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_004_9__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_129), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_125), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_116), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_200), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_191));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_0__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_155));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_1__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_153));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_2__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_135));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_3__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_155), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_133));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_4__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_153), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_123));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_5__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_135), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_133), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_121));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_6__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_123), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_115), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_114));
  ADDFHX2HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_005_7__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_121), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_117), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_114), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_201), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_192));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_006_0__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_152));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_006_1__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_131));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_006_2__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_152), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_131), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_119));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_006_3__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_113), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_112));
  ADDFX2HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_006_4__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_119), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_112), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_115), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_202), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_193));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_007_0__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_203), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_118));
  ADDFX2HVT WALLACE_CSA_DUMMY_OP_groupi_cdnfadd_007_1__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_118), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_113), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_195), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_194));
  OAI2BB1X4HVT WALLACE_CSA_DUMMY_OP_groupi_g586__2398(.A0N
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .A1N
       (WALLACE_CSA_DUMMY_OP_groupi_n_109), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .Y (n_44));
  XNOR2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g587__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .Y (n_45));
  INVX3HVT WALLACE_CSA_DUMMY_OP_groupi_g588(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_109));
  AOI2BB1X4HVT WALLACE_CSA_DUMMY_OP_groupi_g589__6260(.A0N
       (WALLACE_CSA_DUMMY_OP_groupi_n_89), .A1N
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_108));
  XNOR2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g590__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_98), .Y (n_46));
  AOI2BB1X4HVT WALLACE_CSA_DUMMY_OP_groupi_g591__8428(.A0N
       (WALLACE_CSA_DUMMY_OP_groupi_n_95), .A1N
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_106));
  XNOR2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g592__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_100), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .Y (n_47));
  AOI2BB1X4HVT WALLACE_CSA_DUMMY_OP_groupi_g593__6783(.A0N
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .A1N
       (WALLACE_CSA_DUMMY_OP_groupi_n_101), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_91), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_104));
  XNOR2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g594__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_99), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_101), .Y (n_48));
  CLKXOR2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g595__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .Y (n_49));
  AOI2BB1X4HVT WALLACE_CSA_DUMMY_OP_groupi_g596__2802(.A0N
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .A1N
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_101));
  NOR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g597__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_95), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_100));
  NOR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g598__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_91), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_99));
  NOR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g599__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_89), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_98));
  NOR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g600__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_97));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g601__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_96));
  NOR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g602__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_201), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_193), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_95));
  AND2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g603__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_201), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_193), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_94));
  NOR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g604__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_200), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_192), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_93));
  AND2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g605__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_194), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_202), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_92));
  CLKAND2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g606__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_200), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_192), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_91));
  NOR2X6HVT WALLACE_CSA_DUMMY_OP_groupi_g607__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_199), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_191), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_90));
  NOR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g608__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_194), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_202), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_89));
  CLKAND2X3HVT WALLACE_CSA_DUMMY_OP_groupi_g609__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_199), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_191), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_88));
  OR2X2HVT WALLACE_CSA_DUMMY_OP_groupi_g610__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_87));
  NAND2X4HVT WALLACE_CSA_DUMMY_OP_groupi_g611__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_86));
  INVX2HVT WALLACE_CSA_DUMMY_OP_groupi_g612(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_195), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_85));
  INVX3HVT WALLACE_CSA_DUMMY_OP_groupi_g613(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_84));
  ADDFHX2HVT WALLACE_CSA_DUMMY_OP_groupi_g614__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_198), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_190), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .S (n_50));
  ADDFHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g615__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_197), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_189), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .S (n_51));
  INVX2HVT WALLACE_CSA_DUMMY_OP_groupi_g616(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_203), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  ADDFX1HVT WALLACE_CSA_DUMMY_OP_groupi_g617__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_196), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_188), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .S (n_52));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g618__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_187), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_76));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g619__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_74));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g620__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_72));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g621__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_70));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g622__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_68));
  ADDHX1HVT WALLACE_CSA_DUMMY_OP_groupi_g623__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_66));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g624__6783(.A (C1[1]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_64));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g625__3680(.A (C0[2]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g626__1617(.A (C2[3]), .B
       (X2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g627__2802(.A (C2[3]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_61));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g628__1705(.A (X2[1]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g629__5122(.A (C0[1]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g630__8246(.A (C1[3]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g631__7098(.A (X2[0]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_57));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g632__6131(.A (X3[2]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g633__1881(.A (C0[0]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g634__5115(.A (X3[0]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_54));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g635__7482(.A (X0[0]), .B
       (C0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_53));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g636__4733(.A (X1[0]), .B
       (C1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g637__6161(.A (C2[2]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g638__9315(.A (C1[3]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g639__9945(.A (X1[2]), .B
       (C1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g640__2883(.A (C0[2]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_48));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g641__2346(.A (X0[0]), .B
       (C0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g642__1666(.A (C0[2]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g643__7410(.A (C2[0]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g644__6417(.A (X2[1]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g645__5477(.A (X2[1]), .B
       (C2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g646__2398(.A (C2[1]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g647__5107(.A (X3[3]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g648__6260(.A (C0[3]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g649__4319(.A (X1[1]), .B
       (C1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g650__8428(.A (X1[0]), .B
       (C1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g651__5526(.A (X0[1]), .B
       (C0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g652__6783(.A (C1[3]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g653__3680(.A (X0[3]), .B
       (C0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g654__1617(.A (X3[1]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g655__2802(.A (C2[3]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g656__1705(.A (X0[1]), .B
       (C0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g657__5122(.A (C0[3]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g658__8246(.A (X1[1]), .B
       (C1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g659__7098(.A (C1[2]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g660__6131(.A (X3[1]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g661__1881(.A (X2[3]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g662__5115(.A (C0[3]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g663__7482(.A (C3[1]), .B
       (X3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  CLKAND2X3HVT WALLACE_CSA_DUMMY_OP_groupi_g664__4733(.A (X0[2]), .B
       (C0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g665__6161(.A (X2[3]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g666__9315(.A (X1[3]), .B
       (C1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g667__9945(.A (X3[2]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g668__2883(.A (X2[0]), .B
       (C2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g669__2346(.A (X1[0]), .B
       (C1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g670__1666(.A (X1[2]), .B
       (C1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  CLKAND2X3HVT WALLACE_CSA_DUMMY_OP_groupi_g671__7410(.A (X0[1]), .B
       (C0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g672__6417(.A (X1[3]), .B
       (C1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  CLKAND2X3HVT WALLACE_CSA_DUMMY_OP_groupi_g673__5477(.A (X0[2]), .B
       (C0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  CLKAND2X3HVT WALLACE_CSA_DUMMY_OP_groupi_g674__2398(.A (X3[0]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g675__5107(.A (C1[0]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g676__6260(.A (C1[2]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g677__4319(.A (X2[0]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g678__8428(.A (C2[1]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g679__5526(.A (X3[2]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g680__6783(.A (C2[0]), .B
       (X2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g681__3680(.A (C3[3]), .B
       (X3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g682__1617(.A (X3[0]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g683__2802(.A (X3[0]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g684__1705(.A (C3[3]), .B
       (X3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g685__5122(.A (C3[2]), .B
       (X3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g686__8246(.A (X3[1]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2X1HVT WALLACE_CSA_DUMMY_OP_groupi_g687__7098(.A (X3[1]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
endmodule

