###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Sat May  2 12:26:22 2026
#  Design:            MAC_4BIT
#  Command:           saveDesign DBS/signoff.enc
###############################################################
current_design MAC_4BIT
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {SYS_CLOCK}]  -name SYS_CLOCK -period 10.000000 -waveform {0.000000 5.000000}
set_propagated_clock  [get_ports {SYS_CLOCK}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {A[3]}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {A[1]}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {B[3]}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {B[1]}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {A[2]}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {A[0]}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {SRST}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {B[2]}]
set_input_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {B[0]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[7]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[5]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[3]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[1]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[6]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[4]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[2]}]
set_output_delay -add_delay 0 -clock [get_clocks {SYS_CLOCK}] [get_ports {Y[0]}]
set_false_path  -from [get_ports {SRST}] 
