/*
###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Mon Jun 15 19:37:42 2026
#  Design:            RISC_V3
#  Command:           saveNetlist final/RISC_V3.v
###############################################################
*/
module RISC_V3 (
	SYS_CLOCK, 
	RST, 
	DM_IN, 
	PC, 
	DM_ADDR, 
	DM_WR, 
	IR, 
	ACCUM_R, 
	PSTATE);
   input SYS_CLOCK;
   input RST;
   output [31:0] DM_IN;
   output [3:0] PC;
   output [3:0] DM_ADDR;
   output DM_WR;
   output [31:0] IR;
   output [31:0] ACCUM_R;
   output [2:0] PSTATE;

   // Internal wires
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;

   assign PSTATE[2] = 1'b0 ;
   assign ACCUM_R[0] = 1'b0 ;
   assign ACCUM_R[1] = 1'b0 ;
   assign ACCUM_R[2] = 1'b0 ;
   assign ACCUM_R[3] = 1'b0 ;
   assign ACCUM_R[4] = 1'b0 ;
   assign ACCUM_R[5] = 1'b0 ;
   assign ACCUM_R[6] = 1'b0 ;
   assign ACCUM_R[7] = 1'b0 ;
   assign ACCUM_R[8] = 1'b0 ;
   assign ACCUM_R[9] = 1'b0 ;
   assign ACCUM_R[10] = 1'b0 ;
   assign ACCUM_R[11] = 1'b0 ;
   assign ACCUM_R[12] = 1'b0 ;
   assign ACCUM_R[13] = 1'b0 ;
   assign ACCUM_R[14] = 1'b0 ;
   assign ACCUM_R[15] = 1'b0 ;
   assign ACCUM_R[16] = 1'b0 ;
   assign ACCUM_R[17] = 1'b0 ;
   assign ACCUM_R[18] = 1'b0 ;
   assign ACCUM_R[19] = 1'b0 ;
   assign ACCUM_R[20] = 1'b0 ;
   assign ACCUM_R[21] = 1'b0 ;
   assign ACCUM_R[22] = 1'b0 ;
   assign ACCUM_R[23] = 1'b0 ;
   assign ACCUM_R[24] = 1'b0 ;
   assign ACCUM_R[25] = 1'b0 ;
   assign ACCUM_R[26] = 1'b0 ;
   assign ACCUM_R[27] = 1'b0 ;
   assign ACCUM_R[28] = 1'b0 ;
   assign ACCUM_R[29] = 1'b0 ;
   assign ACCUM_R[30] = 1'b0 ;
   assign ACCUM_R[31] = 1'b0 ;
   assign IR[0] = 1'b0 ;
   assign IR[1] = 1'b0 ;
   assign IR[2] = 1'b0 ;
   assign IR[3] = 1'b0 ;
   assign IR[4] = 1'b0 ;
   assign IR[5] = 1'b0 ;
   assign IR[6] = 1'b0 ;
   assign IR[7] = 1'b0 ;
   assign IR[8] = 1'b0 ;
   assign IR[9] = 1'b0 ;
   assign IR[10] = 1'b0 ;
   assign IR[11] = 1'b0 ;
   assign IR[12] = 1'b0 ;
   assign IR[13] = 1'b0 ;
   assign IR[14] = 1'b0 ;
   assign IR[15] = 1'b0 ;
   assign IR[16] = 1'b0 ;
   assign IR[17] = 1'b0 ;
   assign IR[18] = 1'b0 ;
   assign IR[19] = 1'b0 ;
   assign IR[20] = 1'b0 ;
   assign IR[21] = 1'b0 ;
   assign IR[22] = 1'b0 ;
   assign IR[23] = 1'b0 ;
   assign IR[24] = 1'b0 ;
   assign IR[25] = 1'b0 ;
   assign IR[26] = 1'b0 ;
   assign IR[27] = 1'b0 ;
   assign IR[28] = 1'b0 ;
   assign IR[29] = 1'b0 ;
   assign IR[30] = 1'b0 ;
   assign IR[31] = 1'b0 ;
   assign DM_WR = 1'b0 ;
   assign DM_ADDR[0] = 1'b0 ;
   assign DM_ADDR[1] = 1'b0 ;
   assign DM_ADDR[2] = 1'b0 ;
   assign DM_ADDR[3] = 1'b0 ;
   assign DM_IN[0] = 1'b0 ;
   assign DM_IN[1] = 1'b0 ;
   assign DM_IN[2] = 1'b0 ;
   assign DM_IN[3] = 1'b0 ;
   assign DM_IN[4] = 1'b0 ;
   assign DM_IN[5] = 1'b0 ;
   assign DM_IN[6] = 1'b0 ;
   assign DM_IN[7] = 1'b0 ;
   assign DM_IN[8] = 1'b0 ;
   assign DM_IN[9] = 1'b0 ;
   assign DM_IN[10] = 1'b0 ;
   assign DM_IN[11] = 1'b0 ;
   assign DM_IN[12] = 1'b0 ;
   assign DM_IN[13] = 1'b0 ;
   assign DM_IN[14] = 1'b0 ;
   assign DM_IN[15] = 1'b0 ;
   assign DM_IN[16] = 1'b0 ;
   assign DM_IN[17] = 1'b0 ;
   assign DM_IN[18] = 1'b0 ;
   assign DM_IN[19] = 1'b0 ;
   assign DM_IN[20] = 1'b0 ;
   assign DM_IN[21] = 1'b0 ;
   assign DM_IN[22] = 1'b0 ;
   assign DM_IN[23] = 1'b0 ;
   assign DM_IN[24] = 1'b0 ;
   assign DM_IN[25] = 1'b0 ;
   assign DM_IN[26] = 1'b0 ;
   assign DM_IN[27] = 1'b0 ;
   assign DM_IN[28] = 1'b0 ;
   assign DM_IN[29] = 1'b0 ;
   assign DM_IN[30] = 1'b0 ;
   assign DM_IN[31] = 1'b0 ;

   SDFFX1 \PC1_PC_reg[3]  (.Q(PC[3]),
	.QN(UNCONNECTED),
	.CK(SYS_CLOCK),
	.D(n_19),
	.SE(RST),
	.SI(PC[3]));
   SDFFX1 \PC1_PC_reg[2]  (.Q(PC[2]),
	.QN(UNCONNECTED0),
	.CK(SYS_CLOCK),
	.D(n_17),
	.SE(RST),
	.SI(PC[2]));
   SDFFX1 \PC1_PC_reg[1]  (.Q(PC[1]),
	.QN(UNCONNECTED1),
	.CK(SYS_CLOCK),
	.D(n_16),
	.SE(RST),
	.SI(PC[1]));
   CLKINVX1 g22259 (.Y(n_19),
	.A(n_18));
   AOI21X1 g22260__2398 (.Y(n_18),
	.A0(PC[3]),
	.A1(n_14),
	.B0(n_12));
   SDFFX1 \PC1_PC_reg[0]  (.Q(PC[0]),
	.QN(UNCONNECTED2),
	.CK(SYS_CLOCK),
	.D(n_8),
	.SE(RST),
	.SI(PC[0]));
   OAI21X1 g22262__5107 (.Y(n_17),
	.A0(n_11),
	.A1(n_13),
	.B0(n_15));
   OAI21X1 g22263__6260 (.Y(n_16),
	.A0(n_5),
	.A1(n_2),
	.B0(n_6));
   DFFX1 \PC1_PSTATE_reg[1]  (.Q(PSTATE[1]),
	.QN(UNCONNECTED3),
	.CK(SYS_CLOCK),
	.D(n_7));
   OR3X1 g22266__4319 (.Y(n_15),
	.A(PC[2]),
	.B(n_10),
	.C(n_9));
   OAI21X1 g22264__8428 (.Y(n_14),
	.A0(PC[2]),
	.A1(n_1),
	.B0(n_13));
   NOR4X1 g22267__5526 (.Y(n_12),
	.A(PC[3]),
	.B(n_11),
	.C(n_10),
	.D(n_9));
   DFFX1 \PC1_PSTATE_reg[0]  (.Q(PSTATE[0]),
	.QN(n_1),
	.CK(SYS_CLOCK),
	.D(n_3));
   MX2X1 g22265__6783 (.Y(n_8),
	.A(n_4),
	.B(PSTATE[1]),
	.S0(PC[0]));
   NOR2X1 g22272__3680 (.Y(n_7),
	.A(RST),
	.B(n_9));
   NAND3X1 g22273__1617 (.Y(n_6),
	.A(PC[0]),
	.B(n_5),
	.C(n_4));
   AOI21X1 g22268__2802 (.Y(n_13),
	.A0(n_10),
	.A1(PSTATE[0]),
	.B0(PSTATE[1]));
   NOR2X1 g22271__1705 (.Y(n_3),
	.A(RST),
	.B(n_4));
   CLKINVX1 g22275 (.Y(n_9),
	.A(n_4));
   AOI21X1 g22274__5122 (.Y(n_2),
	.A0(n_0),
	.A1(PSTATE[0]),
	.B0(PSTATE[1]));
   NOR2X1 g22276__8246 (.Y(n_4),
	.A(PSTATE[1]),
	.B(n_1));
   NAND2X1 g22277__7098 (.Y(n_10),
	.A(PC[1]),
	.B(PC[0]));
   CLKINVX1 g22280 (.Y(n_0),
	.A(PC[0]));
   CLKINVX1 g22281 (.Y(n_11),
	.A(PC[2]));
   CLKINVX1 g22279 (.Y(n_5),
	.A(PC[1]));
endmodule

