
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  2 2026 10:46:01 +06 (May  2 2026 04:46:01 UTC)

// Verification Directory fv/top 

module top(SYS_CLOCK, SRST, X0, X1, X2, X3, C0, C1, C2, C3, Y);
  input SYS_CLOCK, SRST;
  input [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  output [9:0] Y;
  wire SYS_CLOCK, SRST;
  wire [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  wire [9:0] Y;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6, WALLACE_CSA_DUMMY_OP_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_8,
       WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_24,
       WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_32,
       WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_48,
       WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_57,
       WALLACE_CSA_DUMMY_OP_groupi_n_58,
       WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66,
       WALLACE_CSA_DUMMY_OP_groupi_n_67,
       WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_72,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74,
       WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_76,
       WALLACE_CSA_DUMMY_OP_groupi_n_77,
       WALLACE_CSA_DUMMY_OP_groupi_n_78,
       WALLACE_CSA_DUMMY_OP_groupi_n_79;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_80,
       WALLACE_CSA_DUMMY_OP_groupi_n_81,
       WALLACE_CSA_DUMMY_OP_groupi_n_82,
       WALLACE_CSA_DUMMY_OP_groupi_n_83,
       WALLACE_CSA_DUMMY_OP_groupi_n_84,
       WALLACE_CSA_DUMMY_OP_groupi_n_85,
       WALLACE_CSA_DUMMY_OP_groupi_n_86,
       WALLACE_CSA_DUMMY_OP_groupi_n_87;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_88,
       WALLACE_CSA_DUMMY_OP_groupi_n_89,
       WALLACE_CSA_DUMMY_OP_groupi_n_90,
       WALLACE_CSA_DUMMY_OP_groupi_n_91,
       WALLACE_CSA_DUMMY_OP_groupi_n_92,
       WALLACE_CSA_DUMMY_OP_groupi_n_93,
       WALLACE_CSA_DUMMY_OP_groupi_n_94,
       WALLACE_CSA_DUMMY_OP_groupi_n_95;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_96,
       WALLACE_CSA_DUMMY_OP_groupi_n_97,
       WALLACE_CSA_DUMMY_OP_groupi_n_98,
       WALLACE_CSA_DUMMY_OP_groupi_n_99,
       WALLACE_CSA_DUMMY_OP_groupi_n_100,
       WALLACE_CSA_DUMMY_OP_groupi_n_101,
       WALLACE_CSA_DUMMY_OP_groupi_n_102,
       WALLACE_CSA_DUMMY_OP_groupi_n_103;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_104,
       WALLACE_CSA_DUMMY_OP_groupi_n_105,
       WALLACE_CSA_DUMMY_OP_groupi_n_106,
       WALLACE_CSA_DUMMY_OP_groupi_n_107,
       WALLACE_CSA_DUMMY_OP_groupi_n_108,
       WALLACE_CSA_DUMMY_OP_groupi_n_109,
       WALLACE_CSA_DUMMY_OP_groupi_n_110,
       WALLACE_CSA_DUMMY_OP_groupi_n_111;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_112,
       WALLACE_CSA_DUMMY_OP_groupi_n_114,
       WALLACE_CSA_DUMMY_OP_groupi_n_115,
       WALLACE_CSA_DUMMY_OP_groupi_n_116,
       WALLACE_CSA_DUMMY_OP_groupi_n_117,
       WALLACE_CSA_DUMMY_OP_groupi_n_118,
       WALLACE_CSA_DUMMY_OP_groupi_n_119,
       WALLACE_CSA_DUMMY_OP_groupi_n_120;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_121,
       WALLACE_CSA_DUMMY_OP_groupi_n_122,
       WALLACE_CSA_DUMMY_OP_groupi_n_123,
       WALLACE_CSA_DUMMY_OP_groupi_n_124,
       WALLACE_CSA_DUMMY_OP_groupi_n_125,
       WALLACE_CSA_DUMMY_OP_groupi_n_126,
       WALLACE_CSA_DUMMY_OP_groupi_n_127,
       WALLACE_CSA_DUMMY_OP_groupi_n_128;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_129,
       WALLACE_CSA_DUMMY_OP_groupi_n_130,
       WALLACE_CSA_DUMMY_OP_groupi_n_131,
       WALLACE_CSA_DUMMY_OP_groupi_n_132,
       WALLACE_CSA_DUMMY_OP_groupi_n_133,
       WALLACE_CSA_DUMMY_OP_groupi_n_134,
       WALLACE_CSA_DUMMY_OP_groupi_n_135,
       WALLACE_CSA_DUMMY_OP_groupi_n_136;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_137,
       WALLACE_CSA_DUMMY_OP_groupi_n_138,
       WALLACE_CSA_DUMMY_OP_groupi_n_139,
       WALLACE_CSA_DUMMY_OP_groupi_n_140,
       WALLACE_CSA_DUMMY_OP_groupi_n_141,
       WALLACE_CSA_DUMMY_OP_groupi_n_142,
       WALLACE_CSA_DUMMY_OP_groupi_n_143,
       WALLACE_CSA_DUMMY_OP_groupi_n_144;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_146,
       WALLACE_CSA_DUMMY_OP_groupi_n_147,
       WALLACE_CSA_DUMMY_OP_groupi_n_148,
       WALLACE_CSA_DUMMY_OP_groupi_n_149,
       WALLACE_CSA_DUMMY_OP_groupi_n_150,
       WALLACE_CSA_DUMMY_OP_groupi_n_151,
       WALLACE_CSA_DUMMY_OP_groupi_n_152,
       WALLACE_CSA_DUMMY_OP_groupi_n_153;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_154,
       WALLACE_CSA_DUMMY_OP_groupi_n_155,
       WALLACE_CSA_DUMMY_OP_groupi_n_156,
       WALLACE_CSA_DUMMY_OP_groupi_n_157,
       WALLACE_CSA_DUMMY_OP_groupi_n_158,
       WALLACE_CSA_DUMMY_OP_groupi_n_159,
       WALLACE_CSA_DUMMY_OP_groupi_n_160,
       WALLACE_CSA_DUMMY_OP_groupi_n_161;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_162,
       WALLACE_CSA_DUMMY_OP_groupi_n_164,
       WALLACE_CSA_DUMMY_OP_groupi_n_165,
       WALLACE_CSA_DUMMY_OP_groupi_n_166,
       WALLACE_CSA_DUMMY_OP_groupi_n_167,
       WALLACE_CSA_DUMMY_OP_groupi_n_168,
       WALLACE_CSA_DUMMY_OP_groupi_n_169,
       WALLACE_CSA_DUMMY_OP_groupi_n_170;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_172,
       WALLACE_CSA_DUMMY_OP_groupi_n_173,
       WALLACE_CSA_DUMMY_OP_groupi_n_174,
       WALLACE_CSA_DUMMY_OP_groupi_n_176,
       WALLACE_CSA_DUMMY_OP_groupi_n_178,
       WALLACE_CSA_DUMMY_OP_groupi_n_180, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52;
  DFFQXL \Y_reg[9] (.CK (SYS_CLOCK), .D (n_8), .Q (Y[9]));
  DFFQXL \Y_reg[8] (.CK (SYS_CLOCK), .D (n_7), .Q (Y[8]));
  DFFQXL \Y_reg[6] (.CK (SYS_CLOCK), .D (n_6), .Q (Y[6]));
  DFFQXL \Y_reg[2] (.CK (SYS_CLOCK), .D (n_4), .Q (Y[2]));
  DFFQXL \Y_reg[1] (.CK (SYS_CLOCK), .D (n_1), .Q (Y[1]));
  DFFQXL \Y_reg[5] (.CK (SYS_CLOCK), .D (n_5), .Q (Y[5]));
  DFFQXL \Y_reg[0] (.CK (SYS_CLOCK), .D (n_0), .Q (Y[0]));
  DFFQXL \Y_reg[7] (.CK (SYS_CLOCK), .D (n_9), .Q (Y[7]));
  DFFQXL \Y_reg[4] (.CK (SYS_CLOCK), .D (n_2), .Q (Y[4]));
  DFFQXL \Y_reg[3] (.CK (SYS_CLOCK), .D (n_3), .Q (Y[3]));
  NOR2BX1 g37__2398(.AN (n_45), .B (SRST), .Y (n_9));
  NOR2BX1 g38__5107(.AN (n_43), .B (SRST), .Y (n_8));
  NOR2BX1 g39__6260(.AN (n_44), .B (SRST), .Y (n_7));
  NOR2BX1 g40__4319(.AN (n_46), .B (SRST), .Y (n_6));
  NOR2BX1 g41__8428(.AN (n_47), .B (SRST), .Y (n_5));
  NOR2BX1 g42__5526(.AN (n_50), .B (SRST), .Y (n_4));
  NOR2BX1 g43__6783(.AN (n_49), .B (SRST), .Y (n_3));
  NOR2BX1 g44__3680(.AN (n_48), .B (SRST), .Y (n_2));
  NOR2BX1 g45__1617(.AN (n_51), .B (SRST), .Y (n_1));
  NOR2BX1 g46__2802(.AN (n_52), .B (SRST), .Y (n_0));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3106__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .CO (n_43), .S (n_44));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3107__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_167), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .S (n_45));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3108__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_173), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .S (n_46));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3109__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_169), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .S (n_47));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3110__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_165), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .S (n_48));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3111__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_141), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_159), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_173));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3112__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_149), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_155), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .S (n_49));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3113__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_153), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_161), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_169));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3114__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_137), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_167));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3115__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_143), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_157), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_165));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3116__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_125), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_151), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .S (n_50));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3117__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_147), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_161));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3118__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_152), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_159));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3119__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_116), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_129), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_139), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_157));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3120__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_117), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_119), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_155));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3121__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_115), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_123), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_152), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_153));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3122__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_127), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_151));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3123__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_131), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_149));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3124__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_110), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_147));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3125__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_89), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_112), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_121), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .S (n_51));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3126__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_111), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_133), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_118), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_143));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3127__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_103), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_114), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_135), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_141));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3128__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_95), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_139));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3129__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_102), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_137));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3130__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_135));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3131__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_98), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_133));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3132__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_131));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3133__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_100), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_129));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3134__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_127));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3135__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_81), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_107), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_125));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3136__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_123));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3137__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_105), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_121));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3138__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_101), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_99), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_118), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_119));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3139__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_91), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_109), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_116), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_117));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3140__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_114), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_115));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3141__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_112), .S (n_52));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3142__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_110), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_111));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3143__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_109));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3144__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_107));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3145__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_105));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3146__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_102), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_103));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3147__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_100), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_101));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3148__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_98), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_99));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3149__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_97));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3150__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_95));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3151__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_93));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3152__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_91));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3153__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_89));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3154__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_87));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3155__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_85));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3156__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_83));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3157__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_81));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3158__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3159__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_77));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g3160__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_75));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3161__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_73));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3162__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_71));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3163__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_69));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3164__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_67));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g3165__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_65));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3166__6131(.A (X3[2]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3167__1881(.A (X3[3]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3168__5115(.A (X3[2]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_61));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3169__7482(.A (X2[3]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3170__4733(.A (X2[0]), .B
       (C2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3171__6161(.A (X2[0]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3172__9315(.A (X2[3]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_57));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3173__9945(.A (X0[3]), .B
       (C0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3174__2883(.A (X3[1]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3175__2346(.A (X3[2]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_54));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3176__1666(.A (X3[0]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_53));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3177__7410(.A (X3[0]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3178__6417(.A (X2[1]), .B
       (C2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3179__5477(.A (C0[1]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3180__2398(.A (C1[0]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3181__5107(.A (C3[1]), .B
       (X3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_48));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3182__6260(.A (C0[2]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3183__4319(.A (C0[3]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3184__8428(.A (C1[1]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3185__5526(.A (C0[1]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3186__6783(.A (C0[2]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3187__3680(.A (C0[2]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3188__1617(.A (C1[2]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3189__2802(.A (C0[1]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3190__1705(.A (C2[0]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3191__5122(.A (C0[2]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3192__8246(.A (C0[0]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3193__7098(.A (C0[0]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3194__6131(.A (C0[1]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3195__1881(.A (C1[3]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3196__5115(.A (C2[0]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3197__7482(.A (C0[0]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3198__4733(.A (X3[2]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3199__6161(.A (X3[3]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3200__9315(.A (X2[0]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3201__9945(.A (X2[1]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3202__2883(.A (X3[3]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3203__2346(.A (X3[1]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3204__1666(.A (X3[0]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3205__7410(.A (X3[3]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3206__6417(.A (X3[0]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3207__5477(.A (X1[0]), .B
       (C1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3208__2398(.A (X2[2]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3209__5107(.A (X3[1]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3210__6260(.A (X2[1]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3211__4319(.A (X2[2]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3212__8428(.A (C0[3]), .B
       (X0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3213__5526(.A (C1[1]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3214__6783(.A (C2[1]), .B
       (X2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3215__3680(.A (C1[2]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3216__1617(.A (C1[0]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3217__2802(.A (C0[3]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3218__1705(.A (C1[1]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3219__5122(.A (C0[3]), .B
       (X0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3220__8246(.A (C1[3]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3221__7098(.A (C1[1]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3222__6131(.A (C1[3]), .B
       (X1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3223__1881(.A (C1[0]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3224__5115(.A (C2[2]), .B
       (X2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3225__7482(.A (C1[0]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3226__4733(.A (C2[1]), .B
       (X2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3227__6161(.A (C1[3]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3228__9315(.A (C2[2]), .B
       (X2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g3229__9945(.A (C1[2]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_0));
endmodule

