
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jun 15 2026 19:19:39 +06 (Jun 15 2026 13:19:39 UTC)

// Verification Directory fv/RISC_V3 

module RISC_V3(SYS_CLOCK, RST, DM_IN, PC, DM_ADDR, DM_WR, IR, ACCUM_R,
     PSTATE);
  input SYS_CLOCK, RST;
  output [31:0] DM_IN, IR, ACCUM_R;
  output [3:0] PC, DM_ADDR;
  output DM_WR;
  output [2:0] PSTATE;
  wire SYS_CLOCK, RST;
  wire [31:0] DM_IN, IR, ACCUM_R;
  wire [3:0] PC, DM_ADDR;
  wire DM_WR;
  wire [2:0] PSTATE;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19;
  assign PSTATE[2] = 1'b0;
  assign ACCUM_R[0] = 1'b0;
  assign ACCUM_R[1] = 1'b0;
  assign ACCUM_R[2] = 1'b0;
  assign ACCUM_R[3] = 1'b0;
  assign ACCUM_R[4] = 1'b0;
  assign ACCUM_R[5] = 1'b0;
  assign ACCUM_R[6] = 1'b0;
  assign ACCUM_R[7] = 1'b0;
  assign ACCUM_R[8] = 1'b0;
  assign ACCUM_R[9] = 1'b0;
  assign ACCUM_R[10] = 1'b0;
  assign ACCUM_R[11] = 1'b0;
  assign ACCUM_R[12] = 1'b0;
  assign ACCUM_R[13] = 1'b0;
  assign ACCUM_R[14] = 1'b0;
  assign ACCUM_R[15] = 1'b0;
  assign ACCUM_R[16] = 1'b0;
  assign ACCUM_R[17] = 1'b0;
  assign ACCUM_R[18] = 1'b0;
  assign ACCUM_R[19] = 1'b0;
  assign ACCUM_R[20] = 1'b0;
  assign ACCUM_R[21] = 1'b0;
  assign ACCUM_R[22] = 1'b0;
  assign ACCUM_R[23] = 1'b0;
  assign ACCUM_R[24] = 1'b0;
  assign ACCUM_R[25] = 1'b0;
  assign ACCUM_R[26] = 1'b0;
  assign ACCUM_R[27] = 1'b0;
  assign ACCUM_R[28] = 1'b0;
  assign ACCUM_R[29] = 1'b0;
  assign ACCUM_R[30] = 1'b0;
  assign ACCUM_R[31] = 1'b0;
  assign IR[0] = 1'b0;
  assign IR[1] = 1'b0;
  assign IR[2] = 1'b0;
  assign IR[3] = 1'b0;
  assign IR[4] = 1'b0;
  assign IR[5] = 1'b0;
  assign IR[6] = 1'b0;
  assign IR[7] = 1'b0;
  assign IR[8] = 1'b0;
  assign IR[9] = 1'b0;
  assign IR[10] = 1'b0;
  assign IR[11] = 1'b0;
  assign IR[12] = 1'b0;
  assign IR[13] = 1'b0;
  assign IR[14] = 1'b0;
  assign IR[15] = 1'b0;
  assign IR[16] = 1'b0;
  assign IR[17] = 1'b0;
  assign IR[18] = 1'b0;
  assign IR[19] = 1'b0;
  assign IR[20] = 1'b0;
  assign IR[21] = 1'b0;
  assign IR[22] = 1'b0;
  assign IR[23] = 1'b0;
  assign IR[24] = 1'b0;
  assign IR[25] = 1'b0;
  assign IR[26] = 1'b0;
  assign IR[27] = 1'b0;
  assign IR[28] = 1'b0;
  assign IR[29] = 1'b0;
  assign IR[30] = 1'b0;
  assign IR[31] = 1'b0;
  assign DM_WR = 1'b0;
  assign DM_ADDR[0] = 1'b0;
  assign DM_ADDR[1] = 1'b0;
  assign DM_ADDR[2] = 1'b0;
  assign DM_ADDR[3] = 1'b0;
  assign DM_IN[0] = 1'b0;
  assign DM_IN[1] = 1'b0;
  assign DM_IN[2] = 1'b0;
  assign DM_IN[3] = 1'b0;
  assign DM_IN[4] = 1'b0;
  assign DM_IN[5] = 1'b0;
  assign DM_IN[6] = 1'b0;
  assign DM_IN[7] = 1'b0;
  assign DM_IN[8] = 1'b0;
  assign DM_IN[9] = 1'b0;
  assign DM_IN[10] = 1'b0;
  assign DM_IN[11] = 1'b0;
  assign DM_IN[12] = 1'b0;
  assign DM_IN[13] = 1'b0;
  assign DM_IN[14] = 1'b0;
  assign DM_IN[15] = 1'b0;
  assign DM_IN[16] = 1'b0;
  assign DM_IN[17] = 1'b0;
  assign DM_IN[18] = 1'b0;
  assign DM_IN[19] = 1'b0;
  assign DM_IN[20] = 1'b0;
  assign DM_IN[21] = 1'b0;
  assign DM_IN[22] = 1'b0;
  assign DM_IN[23] = 1'b0;
  assign DM_IN[24] = 1'b0;
  assign DM_IN[25] = 1'b0;
  assign DM_IN[26] = 1'b0;
  assign DM_IN[27] = 1'b0;
  assign DM_IN[28] = 1'b0;
  assign DM_IN[29] = 1'b0;
  assign DM_IN[30] = 1'b0;
  assign DM_IN[31] = 1'b0;
  SDFFX1 \PC1_PC_reg[3] (.CK (SYS_CLOCK), .D (n_19), .SI (PC[3]), .SE
       (RST), .Q (PC[3]), .QN (UNCONNECTED));
  SDFFX1 \PC1_PC_reg[2] (.CK (SYS_CLOCK), .D (n_17), .SI (PC[2]), .SE
       (RST), .Q (PC[2]), .QN (UNCONNECTED0));
  SDFFX1 \PC1_PC_reg[1] (.CK (SYS_CLOCK), .D (n_16), .SI (PC[1]), .SE
       (RST), .Q (PC[1]), .QN (UNCONNECTED1));
  CLKINVX1 g22259(.A (n_18), .Y (n_19));
  AOI21X1 g22260__2398(.A0 (PC[3]), .A1 (n_14), .B0 (n_12), .Y (n_18));
  SDFFX1 \PC1_PC_reg[0] (.CK (SYS_CLOCK), .D (n_8), .SI (PC[0]), .SE
       (RST), .Q (PC[0]), .QN (UNCONNECTED2));
  OAI21X1 g22262__5107(.A0 (n_11), .A1 (n_13), .B0 (n_15), .Y (n_17));
  OAI21X1 g22263__6260(.A0 (n_5), .A1 (n_2), .B0 (n_6), .Y (n_16));
  DFFX1 \PC1_PSTATE_reg[1] (.CK (SYS_CLOCK), .D (n_7), .Q (PSTATE[1]),
       .QN (UNCONNECTED3));
  OR3X1 g22266__4319(.A (PC[2]), .B (n_10), .C (n_9), .Y (n_15));
  OAI21X1 g22264__8428(.A0 (PC[2]), .A1 (n_1), .B0 (n_13), .Y (n_14));
  NOR4X1 g22267__5526(.A (PC[3]), .B (n_11), .C (n_10), .D (n_9), .Y
       (n_12));
  DFFX1 \PC1_PSTATE_reg[0] (.CK (SYS_CLOCK), .D (n_3), .Q (PSTATE[0]),
       .QN (n_1));
  MX2X1 g22265__6783(.A (n_4), .B (PSTATE[1]), .S0 (PC[0]), .Y (n_8));
  NOR2X1 g22272__3680(.A (RST), .B (n_9), .Y (n_7));
  NAND3X1 g22273__1617(.A (PC[0]), .B (n_5), .C (n_4), .Y (n_6));
  AOI21X1 g22268__2802(.A0 (n_10), .A1 (PSTATE[0]), .B0 (PSTATE[1]), .Y
       (n_13));
  NOR2X1 g22271__1705(.A (RST), .B (n_4), .Y (n_3));
  CLKINVX1 g22275(.A (n_4), .Y (n_9));
  AOI21X1 g22274__5122(.A0 (n_0), .A1 (PSTATE[0]), .B0 (PSTATE[1]), .Y
       (n_2));
  NOR2X1 g22276__8246(.A (PSTATE[1]), .B (n_1), .Y (n_4));
  NAND2X1 g22277__7098(.A (PC[1]), .B (PC[0]), .Y (n_10));
  CLKINVX1 g22280(.A (PC[0]), .Y (n_0));
  CLKINVX1 g22281(.A (PC[2]), .Y (n_11));
  CLKINVX1 g22279(.A (PC[1]), .Y (n_5));
endmodule

