
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Apr 18 2026 12:32:02 +06 (Apr 18 2026 06:32:02 UTC)

// Verification Directory fv/MAC_4BIT 

module MAC_4BIT(SYS_CLOCK, SRST, A, B, Y);
  input SYS_CLOCK, SRST;
  input [3:0] A, B;
  output [7:0] Y;
  wire SYS_CLOCK, SRST;
  wire [3:0] A, B;
  wire [7:0] Y;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6, WALLACE_CSA_DUMMY_OP_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_8,
       WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_24,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_32;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_53;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  DFFQX1 \Y_reg[6] (.CK (SYS_CLOCK), .D (n_6), .Q (Y[6]));
  DFFQX1 \Y_reg[1] (.CK (SYS_CLOCK), .D (n_3), .Q (Y[1]));
  DFFQX1 \Y_reg[0] (.CK (SYS_CLOCK), .D (n_0), .Q (Y[0]));
  DFFQX1 \Y_reg[7] (.CK (SYS_CLOCK), .D (n_5), .Q (Y[7]));
  DFFQX1 \Y_reg[4] (.CK (SYS_CLOCK), .D (n_4), .Q (Y[4]));
  DFFQX1 \Y_reg[3] (.CK (SYS_CLOCK), .D (n_1), .Q (Y[3]));
  DFFQX1 \Y_reg[2] (.CK (SYS_CLOCK), .D (n_2), .Q (Y[2]));
  DFFQX1 \Y_reg[5] (.CK (SYS_CLOCK), .D (n_7), .Q (Y[5]));
  NOR2BX1 g22__2398(.AN (n_19), .B (SRST), .Y (n_7));
  NOR2BX1 g23__5107(.AN (n_18), .B (SRST), .Y (n_6));
  NOR2BX1 g24__6260(.AN (n_17), .B (SRST), .Y (n_5));
  NOR2BX1 g25__4319(.AN (n_20), .B (SRST), .Y (n_4));
  NOR2BX1 g26__8428(.AN (n_23), .B (SRST), .Y (n_3));
  NOR2BX1 g27__5526(.AN (n_22), .B (SRST), .Y (n_2));
  NOR2BX1 g28__6783(.AN (n_21), .B (SRST), .Y (n_1));
  NOR2BX1 g29__3680(.AN (n_24), .B (SRST), .Y (n_0));
  XNOR2XL WALLACE_CSA_DUMMY_OP_groupi_g872__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .Y (n_17));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g873__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .S (n_18));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g874__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .S (n_19));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g875__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .S (n_20));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g876__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .CI (Y[3]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .S (n_21));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g877__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CI (Y[5]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g878__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CI (Y[4]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g879__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .CI (Y[2]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .S (n_22));
  XNOR2XL WALLACE_CSA_DUMMY_OP_groupi_g880__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B (Y[7]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g881__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g882__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CI (Y[6]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g883__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g884__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .CI (Y[1]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .S (n_23));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g885__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g886__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  ADDFXL WALLACE_CSA_DUMMY_OP_groupi_g887__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g888__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B (Y[0]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .S (n_24));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g889__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g890__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g891__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  ADDHXL WALLACE_CSA_DUMMY_OP_groupi_g892__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g893__5107(.A (B[1]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g894__6260(.A (B[3]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g895__4319(.A (B[3]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g896__8428(.A (A[3]), .B (B[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g897__5526(.A (A[1]), .B (B[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g898__6783(.A (A[2]), .B (B[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g899__3680(.A (A[2]), .B (B[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g900__1617(.A (A[2]), .B (B[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g901__2802(.A (B[0]), .B (A[1]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g902__1705(.A (B[0]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g903__5122(.A (B[1]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g904__8246(.A (B[2]), .B (A[0]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g905__7098(.A (B[0]), .B (A[3]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g906__6131(.A (B[0]), .B (A[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g907__1881(.A (A[1]), .B (B[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  AND2XL WALLACE_CSA_DUMMY_OP_groupi_g908__5115(.A (A[3]), .B (B[2]),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_0));
endmodule

