
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: May  2 2026 11:31:00 +06 (May  2 2026 05:31:00 UTC)

// Verification Directory fv/top 

module top(SYS_CLOCK, SRST, X0, X1, X2, X3, C0, C1, C2, C3, Y);
  input SYS_CLOCK, SRST;
  input [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  output [9:0] Y;
  wire SYS_CLOCK, SRST;
  wire [3:0] X0, X1, X2, X3, C0, C1, C2, C3;
  wire [9:0] Y;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6, WALLACE_CSA_DUMMY_OP_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_8,
       WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_23;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_24,
       WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_32,
       WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46,
       WALLACE_CSA_DUMMY_OP_groupi_n_47;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_48,
       WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_56,
       WALLACE_CSA_DUMMY_OP_groupi_n_57,
       WALLACE_CSA_DUMMY_OP_groupi_n_58,
       WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_62,
       WALLACE_CSA_DUMMY_OP_groupi_n_63;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66,
       WALLACE_CSA_DUMMY_OP_groupi_n_67,
       WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_72,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_74,
       WALLACE_CSA_DUMMY_OP_groupi_n_75,
       WALLACE_CSA_DUMMY_OP_groupi_n_76,
       WALLACE_CSA_DUMMY_OP_groupi_n_77,
       WALLACE_CSA_DUMMY_OP_groupi_n_78,
       WALLACE_CSA_DUMMY_OP_groupi_n_79;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_80,
       WALLACE_CSA_DUMMY_OP_groupi_n_81,
       WALLACE_CSA_DUMMY_OP_groupi_n_82,
       WALLACE_CSA_DUMMY_OP_groupi_n_83,
       WALLACE_CSA_DUMMY_OP_groupi_n_84,
       WALLACE_CSA_DUMMY_OP_groupi_n_85,
       WALLACE_CSA_DUMMY_OP_groupi_n_86,
       WALLACE_CSA_DUMMY_OP_groupi_n_87;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_88,
       WALLACE_CSA_DUMMY_OP_groupi_n_89,
       WALLACE_CSA_DUMMY_OP_groupi_n_90,
       WALLACE_CSA_DUMMY_OP_groupi_n_91,
       WALLACE_CSA_DUMMY_OP_groupi_n_92,
       WALLACE_CSA_DUMMY_OP_groupi_n_93,
       WALLACE_CSA_DUMMY_OP_groupi_n_94,
       WALLACE_CSA_DUMMY_OP_groupi_n_95;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_96,
       WALLACE_CSA_DUMMY_OP_groupi_n_97,
       WALLACE_CSA_DUMMY_OP_groupi_n_98,
       WALLACE_CSA_DUMMY_OP_groupi_n_99,
       WALLACE_CSA_DUMMY_OP_groupi_n_100,
       WALLACE_CSA_DUMMY_OP_groupi_n_101,
       WALLACE_CSA_DUMMY_OP_groupi_n_102,
       WALLACE_CSA_DUMMY_OP_groupi_n_103;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_104,
       WALLACE_CSA_DUMMY_OP_groupi_n_105,
       WALLACE_CSA_DUMMY_OP_groupi_n_106,
       WALLACE_CSA_DUMMY_OP_groupi_n_107,
       WALLACE_CSA_DUMMY_OP_groupi_n_108,
       WALLACE_CSA_DUMMY_OP_groupi_n_109,
       WALLACE_CSA_DUMMY_OP_groupi_n_110,
       WALLACE_CSA_DUMMY_OP_groupi_n_111;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_112,
       WALLACE_CSA_DUMMY_OP_groupi_n_114,
       WALLACE_CSA_DUMMY_OP_groupi_n_115,
       WALLACE_CSA_DUMMY_OP_groupi_n_116,
       WALLACE_CSA_DUMMY_OP_groupi_n_117,
       WALLACE_CSA_DUMMY_OP_groupi_n_118,
       WALLACE_CSA_DUMMY_OP_groupi_n_119,
       WALLACE_CSA_DUMMY_OP_groupi_n_120;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_121,
       WALLACE_CSA_DUMMY_OP_groupi_n_122,
       WALLACE_CSA_DUMMY_OP_groupi_n_123,
       WALLACE_CSA_DUMMY_OP_groupi_n_124,
       WALLACE_CSA_DUMMY_OP_groupi_n_125,
       WALLACE_CSA_DUMMY_OP_groupi_n_126,
       WALLACE_CSA_DUMMY_OP_groupi_n_127,
       WALLACE_CSA_DUMMY_OP_groupi_n_128;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_129,
       WALLACE_CSA_DUMMY_OP_groupi_n_130,
       WALLACE_CSA_DUMMY_OP_groupi_n_131,
       WALLACE_CSA_DUMMY_OP_groupi_n_132,
       WALLACE_CSA_DUMMY_OP_groupi_n_133,
       WALLACE_CSA_DUMMY_OP_groupi_n_134,
       WALLACE_CSA_DUMMY_OP_groupi_n_135,
       WALLACE_CSA_DUMMY_OP_groupi_n_136;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_137,
       WALLACE_CSA_DUMMY_OP_groupi_n_138,
       WALLACE_CSA_DUMMY_OP_groupi_n_139,
       WALLACE_CSA_DUMMY_OP_groupi_n_140,
       WALLACE_CSA_DUMMY_OP_groupi_n_141,
       WALLACE_CSA_DUMMY_OP_groupi_n_142,
       WALLACE_CSA_DUMMY_OP_groupi_n_143,
       WALLACE_CSA_DUMMY_OP_groupi_n_144;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_145,
       WALLACE_CSA_DUMMY_OP_groupi_n_146,
       WALLACE_CSA_DUMMY_OP_groupi_n_148,
       WALLACE_CSA_DUMMY_OP_groupi_n_149,
       WALLACE_CSA_DUMMY_OP_groupi_n_150,
       WALLACE_CSA_DUMMY_OP_groupi_n_151,
       WALLACE_CSA_DUMMY_OP_groupi_n_152,
       WALLACE_CSA_DUMMY_OP_groupi_n_153;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_154,
       WALLACE_CSA_DUMMY_OP_groupi_n_155,
       WALLACE_CSA_DUMMY_OP_groupi_n_156,
       WALLACE_CSA_DUMMY_OP_groupi_n_157,
       WALLACE_CSA_DUMMY_OP_groupi_n_158,
       WALLACE_CSA_DUMMY_OP_groupi_n_159,
       WALLACE_CSA_DUMMY_OP_groupi_n_160,
       WALLACE_CSA_DUMMY_OP_groupi_n_161;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_162,
       WALLACE_CSA_DUMMY_OP_groupi_n_163,
       WALLACE_CSA_DUMMY_OP_groupi_n_164,
       WALLACE_CSA_DUMMY_OP_groupi_n_165,
       WALLACE_CSA_DUMMY_OP_groupi_n_166,
       WALLACE_CSA_DUMMY_OP_groupi_n_168,
       WALLACE_CSA_DUMMY_OP_groupi_n_169,
       WALLACE_CSA_DUMMY_OP_groupi_n_170;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_171,
       WALLACE_CSA_DUMMY_OP_groupi_n_172,
       WALLACE_CSA_DUMMY_OP_groupi_n_174,
       WALLACE_CSA_DUMMY_OP_groupi_n_176,
       WALLACE_CSA_DUMMY_OP_groupi_n_178,
       WALLACE_CSA_DUMMY_OP_groupi_n_180, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52;
  DFFQXLLVT \Y_reg[9] (.CK (SYS_CLOCK), .D (n_8), .Q (Y[9]));
  DFFQXLLVT \Y_reg[8] (.CK (SYS_CLOCK), .D (n_7), .Q (Y[8]));
  DFFQXLLVT \Y_reg[6] (.CK (SYS_CLOCK), .D (n_6), .Q (Y[6]));
  DFFQXLLVT \Y_reg[2] (.CK (SYS_CLOCK), .D (n_4), .Q (Y[2]));
  DFFQXLLVT \Y_reg[1] (.CK (SYS_CLOCK), .D (n_1), .Q (Y[1]));
  DFFQXLLVT \Y_reg[5] (.CK (SYS_CLOCK), .D (n_5), .Q (Y[5]));
  DFFQXLLVT \Y_reg[0] (.CK (SYS_CLOCK), .D (n_0), .Q (Y[0]));
  DFFQXLLVT \Y_reg[7] (.CK (SYS_CLOCK), .D (n_9), .Q (Y[7]));
  DFFQXLLVT \Y_reg[4] (.CK (SYS_CLOCK), .D (n_2), .Q (Y[4]));
  DFFQXLLVT \Y_reg[3] (.CK (SYS_CLOCK), .D (n_3), .Q (Y[3]));
  NOR2BXLLVT g37__2398(.AN (n_45), .B (SRST), .Y (n_9));
  NOR2BXLLVT g38__5107(.AN (n_43), .B (SRST), .Y (n_8));
  NOR2BXLLVT g39__6260(.AN (n_44), .B (SRST), .Y (n_7));
  NOR2BXLLVT g40__4319(.AN (n_46), .B (SRST), .Y (n_6));
  NOR2BXLLVT g41__8428(.AN (n_47), .B (SRST), .Y (n_5));
  NOR2BXLLVT g42__5526(.AN (n_50), .B (SRST), .Y (n_4));
  NOR2BXLLVT g43__6783(.AN (n_49), .B (SRST), .Y (n_3));
  NOR2BXLLVT g44__3680(.AN (n_48), .B (SRST), .Y (n_2));
  NOR2BXLLVT g45__1617(.AN (n_51), .B (SRST), .Y (n_1));
  NOR2BXLLVT g46__2802(.AN (n_52), .B (SRST), .Y (n_0));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2944__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .CO (n_43), .S (n_44));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2945__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_165), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_180), .S (n_45));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2946__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_171), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_178), .S (n_46));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2947__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_169), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_176), .S (n_47));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2948__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_163), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_174), .S (n_48));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2949__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_161), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_151), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_172), .S (n_49));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2950__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_157), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_149), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_170), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_171));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2951__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_143), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_159), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_168), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_169));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2952__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_129), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_153), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_166), .S (n_50));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2953__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_139), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_164), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_165));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2954__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_145), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_155), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_162), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_163));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2955__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_121), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_123), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_152), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_160), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_161));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2956__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_141), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_158), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_159));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2957__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_156), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_157));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2958__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_117), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_137), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_154), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_155));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2959__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_133), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_75), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_152), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_153));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2960__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_131), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_150), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_151));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2961__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_114), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_107), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_135), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_148), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_149));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2962__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_112), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_125), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_146), .S (n_51));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2963__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_119), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_111), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_144), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_145));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2964__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_127), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_115), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_116), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_142), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_143));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2965__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_110), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_118), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_140), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_141));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2966__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_138), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_139));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2967__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_85), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_136), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_137));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2968__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_134), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_135));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2969__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_102), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_132), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_133));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2970__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_130), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_131));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2971__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_95), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_99), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_109), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_128), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_129));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2972__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_91), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_126), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_127));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2973__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_103), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_124), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_125));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2974__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_81), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_98), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_93), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_122), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_123));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2975__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_101), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_105), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_120), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_121));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2976__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_100), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_118), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_119));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2977__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_87), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_89), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_116), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_117));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2978__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_114), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_115));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2979__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_97), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_112), .S (n_52));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2980__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_110), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_111));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2981__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_108), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_109));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2982__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_106), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_107));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2983__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_67), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_104), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_105));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2984__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_102), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_103));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2985__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_63), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_100), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_101));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2986__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_98), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_99));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2987__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_96), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_97));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2988__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_94), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_95));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2989__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_92), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_93));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2990__2398(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_90), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_91));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2991__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_88), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_89));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2992__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_86), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_87));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2993__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_85));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2994__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_83));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2995__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_81));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2996__6783(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2997__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_77));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2998__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_48), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_74), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_75));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g2999__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_62), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_73));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g3000__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_71));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g3001__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_69));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g3002__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_67));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g3003__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_65));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3004__6131(.A (X2[0]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_63));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3005__1881(.A (X3[0]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_62));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3006__5115(.A (C2[1]), .B
       (X2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_61));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3007__7482(.A (X3[3]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3008__4733(.A (X3[2]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3009__6161(.A (X3[3]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3010__9315(.A (X3[2]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_57));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3011__9945(.A (X3[2]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3012__2883(.A (X0[0]), .B
       (C0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3013__2346(.A (C0[0]), .B
       (X0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_54));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3014__1666(.A (C0[1]), .B
       (X0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_53));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3015__7410(.A (X0[2]), .B
       (C0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3016__6417(.A (X0[1]), .B
       (C0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3017__5477(.A (X0[2]), .B
       (C0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3018__2398(.A (X0[1]), .B
       (C0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_49));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3019__5107(.A (C1[0]), .B
       (X1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_48));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3020__6260(.A (X0[0]), .B
       (C0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3021__4319(.A (X0[0]), .B
       (C0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3022__8428(.A (X0[3]), .B
       (C0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3023__5526(.A (X0[0]), .B
       (C0[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3024__6783(.A (C1[1]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_43));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3025__3680(.A (X1[3]), .B
       (C1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3026__1617(.A (C3[1]), .B
       (X3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3027__2802(.A (X2[2]), .B
       (C2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3028__1705(.A (X1[0]), .B
       (C1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3029__5122(.A (X1[3]), .B
       (C1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3030__8246(.A (X0[3]), .B
       (C0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3031__7098(.A (C1[1]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3032__6131(.A (X0[1]), .B
       (C0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3033__1881(.A (X1[2]), .B
       (C1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3034__5115(.A (X2[3]), .B
       (C2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3035__7482(.A (X1[2]), .B
       (C1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_32));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3036__4733(.A (C3[3]), .B
       (X3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3037__6161(.A (X3[2]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3038__9315(.A (X3[1]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3039__9945(.A (X3[3]), .B
       (C3[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3040__2883(.A (C1[2]), .B
       (X1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3041__2346(.A (X3[0]), .B
       (C3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3042__1666(.A (X2[2]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3043__7410(.A (X3[1]), .B
       (C3[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3044__6417(.A (X2[3]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3045__5477(.A (X2[3]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_22));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3046__2398(.A (X2[0]), .B
       (C2[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3047__5107(.A (C3[2]), .B
       (X3[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3048__6260(.A (X3[3]), .B
       (C3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3049__4319(.A (X2[2]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_18));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3050__8428(.A (X2[1]), .B
       (C2[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3051__5526(.A (C3[2]), .B
       (X3[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3052__6783(.A (X0[3]), .B
       (C0[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3053__3680(.A (X2[1]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3054__1617(.A (X2[0]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3055__2802(.A (X1[1]), .B
       (C1[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3056__1705(.A (X0[3]), .B
       (C0[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3057__5122(.A (X1[3]), .B
       (C1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3058__8246(.A (X1[1]), .B
       (C1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3059__7098(.A (X2[1]), .B
       (C2[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3060__6131(.A (X1[3]), .B
       (C1[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3061__1881(.A (X2[2]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3062__5115(.A (C1[0]), .B
       (X1[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3063__7482(.A (X1[0]), .B
       (C1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3064__4733(.A (X0[2]), .B
       (C0[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3065__6161(.A (C2[2]), .B
       (X2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3066__9315(.A (X1[2]), .B
       (C1[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g3067__9945(.A (X2[3]), .B
       (C2[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_0));
endmodule

