
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Apr 25 2026 13:47:41 +06 (Apr 25 2026 07:47:41 UTC)

// Verification Directory fv/MAC_4BIT 

module MAC_4BIT(SYS_CLOCK, SRST, A, B, Y);
  input SYS_CLOCK, SRST;
  input [3:0] A, B;
  output [7:0] Y;
  wire SYS_CLOCK, SRST;
  wire [3:0] A, B;
  wire [7:0] Y;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_4,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_6, WALLACE_CSA_DUMMY_OP_groupi_n_7;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_8,
       WALLACE_CSA_DUMMY_OP_groupi_n_9,
       WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_17,
       WALLACE_CSA_DUMMY_OP_groupi_n_18,
       WALLACE_CSA_DUMMY_OP_groupi_n_19,
       WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_22,
       WALLACE_CSA_DUMMY_OP_groupi_n_24;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28,
       WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_32;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37,
       WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_43,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_49,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_53;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  DFFQXLLVT \Y_reg[6] (.CK (SYS_CLOCK), .D (n_6), .Q (Y[6]));
  DFFQXLLVT \Y_reg[1] (.CK (SYS_CLOCK), .D (n_3), .Q (Y[1]));
  DFFQXLLVT \Y_reg[0] (.CK (SYS_CLOCK), .D (n_0), .Q (Y[0]));
  DFFQXLLVT \Y_reg[7] (.CK (SYS_CLOCK), .D (n_5), .Q (Y[7]));
  DFFQXLLVT \Y_reg[4] (.CK (SYS_CLOCK), .D (n_4), .Q (Y[4]));
  DFFQXLLVT \Y_reg[3] (.CK (SYS_CLOCK), .D (n_1), .Q (Y[3]));
  DFFQXLLVT \Y_reg[2] (.CK (SYS_CLOCK), .D (n_2), .Q (Y[2]));
  DFFQXLLVT \Y_reg[5] (.CK (SYS_CLOCK), .D (n_7), .Q (Y[5]));
  NOR2BXLLVT g22__2398(.AN (n_19), .B (SRST), .Y (n_7));
  NOR2BXLLVT g23__5107(.AN (n_18), .B (SRST), .Y (n_6));
  NOR2BXLLVT g24__6260(.AN (n_17), .B (SRST), .Y (n_5));
  NOR2BXLLVT g25__4319(.AN (n_20), .B (SRST), .Y (n_4));
  NOR2BXLLVT g26__8428(.AN (n_23), .B (SRST), .Y (n_3));
  NOR2BXLLVT g27__5526(.AN (n_22), .B (SRST), .Y (n_2));
  NOR2BXLLVT g28__6783(.AN (n_21), .B (SRST), .Y (n_1));
  NOR2BXLLVT g29__3680(.AN (n_24), .B (SRST), .Y (n_0));
  XNOR2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g844__1617(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .Y (n_17));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g845__2802(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .S (n_18));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g846__1705(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .S (n_19));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g847__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_49), .S (n_20));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g848__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .S (n_21));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g849__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .CI (Y[2]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .S (n_22));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g850__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .CI (Y[5]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_43), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_44));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g851__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .CI (Y[4]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g852__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .CI (Y[3]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  XNOR2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g853__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .B (Y[7]), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g854__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .CI (Y[6]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g855__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g856__9315(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_17), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .CI (Y[1]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_32), .S (n_23));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g857__9945(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g858__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  ADDFXLLVT WALLACE_CSA_DUMMY_OP_groupi_g859__2346(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .CI
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g860__1666(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_4), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g861__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_7), .B (Y[0]), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_22), .S (n_24));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g862__6417(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_6), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  ADDHXLLVT WALLACE_CSA_DUMMY_OP_groupi_g863__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_18), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  AOI21X1LVT WALLACE_CSA_DUMMY_OP_groupi_g864__2398(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_17));
  NOR2X1LVT WALLACE_CSA_DUMMY_OP_groupi_g865__5107(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  NAND2X1LVT WALLACE_CSA_DUMMY_OP_groupi_g866__6260(.A (B[1]), .B
       (A[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  NAND2X1LVT WALLACE_CSA_DUMMY_OP_groupi_g867__4319(.A (B[0]), .B
       (A[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g868__8428(.A (B[2]), .B
       (A[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g869__5526(.A (B[1]), .B
       (A[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g870__6783(.A (B[3]), .B
       (A[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g871__3680(.A (B[2]), .B
       (A[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g872__1617(.A (B[1]), .B
       (A[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g873__2802(.A (B[1]), .B
       (A[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g874__1705(.A (B[0]), .B
       (A[0]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_7));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g875__5122(.A (B[0]), .B
       (A[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_6));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g876__8246(.A (B[0]), .B
       (A[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g877__7098(.A (B[3]), .B
       (A[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_4));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g878__6131(.A (B[3]), .B
       (A[3]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g879__1881(.A (B[2]), .B
       (A[1]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g880__5115(.A (B[2]), .B
       (A[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  AND2XLLVT WALLACE_CSA_DUMMY_OP_groupi_g881__7482(.A (B[3]), .B
       (A[2]), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_0));
endmodule

